// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matVecMul_matVecMul,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.831000,HLS_SYN_LAT=20742,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=431,HLS_SYN_LUT=917,HLS_VERSION=2021_1}" *)

module matVecMul (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 14;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [11:0] A_address0;
reg    A_ce0;
wire  signed [15:0] A_q0;
wire   [31:0] row_size;
wire   [31:0] col_size;
reg   [5:0] x_localbuff_V_address0;
reg    x_localbuff_V_ce0;
reg    x_localbuff_V_we0;
wire  signed [15:0] x_localbuff_V_q0;
reg    out_stream_TDATA_blk_n;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln39_fu_327_p2;
wire    ap_CS_fsm_state11;
reg   [31:0] col_size_read_reg_705;
reg   [31:0] row_size_read_reg_711;
wire   [31:0] sub_fu_287_p2;
reg   [31:0] sub_reg_717;
wire    ap_CS_fsm_state4;
wire   [31:0] add_ln34_fu_300_p2;
reg   [31:0] add_ln34_reg_728;
wire    ap_CS_fsm_state5;
wire   [12:0] shl_ln_fu_310_p3;
reg   [12:0] shl_ln_reg_733;
wire   [0:0] icmp_ln34_fu_295_p2;
wire   [6:0] add_ln39_fu_332_p2;
reg   [6:0] add_ln39_reg_741;
reg    ap_block_state6;
reg    ap_block_state6_io;
wire    ap_CS_fsm_state7;
wire   [37:0] acc_V_fu_682_p3;
wire    ap_CS_fsm_state10;
wire    grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start;
wire    grp_matVecMul_Pipeline_sample_loop_fu_261_ap_done;
wire    grp_matVecMul_Pipeline_sample_loop_fu_261_ap_idle;
wire    grp_matVecMul_Pipeline_sample_loop_fu_261_ap_ready;
wire    grp_matVecMul_Pipeline_sample_loop_fu_261_in_stream_TREADY;
wire   [5:0] grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_address0;
wire    grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_ce0;
wire    grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_we0;
wire   [15:0] grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_d0;
reg   [6:0] j_reg_238;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg  signed [37:0] acc_V_3_reg_249;
reg    grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln1169_1_fu_377_p1;
wire   [63:0] zext_ln39_1_fu_322_p1;
reg   [31:0] i_1_fu_166;
wire   [5:0] trunc_ln1169_fu_306_p1;
wire   [31:0] zext_ln39_fu_318_p1;
wire   [7:0] shl_ln1169_1_fu_338_p3;
wire   [12:0] zext_ln1169_fu_346_p1;
wire   [12:0] add_ln1169_fu_350_p2;
wire   [5:0] lshr_ln_fu_355_p4;
wire   [5:0] trunc_ln1169_1_fu_365_p1;
wire   [11:0] tmp_9_fu_369_p3;
wire   [0:0] tmp_fu_408_p3;
wire   [15:0] zext_ln415_fu_416_p1;
wire   [15:0] p_Val2_s_fu_390_p4;
wire   [15:0] p_Val2_1_fu_420_p2;
wire   [0:0] p_Result_4_fu_426_p3;
wire   [0:0] p_Result_3_fu_400_p3;
wire   [0:0] xor_ln416_fu_434_p2;
wire   [12:0] p_Result_7_fu_446_p4;
wire   [13:0] p_Result_8_fu_462_p4;
wire   [0:0] carry_1_fu_440_p2;
wire   [0:0] Range1_all_ones_fu_472_p2;
wire   [0:0] Range1_all_zeros_fu_478_p2;
wire   [0:0] tmp_2_fu_492_p3;
wire   [0:0] Range2_all_ones_fu_456_p2;
wire   [0:0] xor_ln789_fu_500_p2;
wire   [0:0] and_ln789_fu_506_p2;
wire   [0:0] deleted_zeros_fu_484_p3;
wire   [0:0] xor_ln794_1_fu_526_p2;
wire   [0:0] p_Result_2_fu_382_p3;
wire   [0:0] or_ln794_fu_532_p2;
wire   [0:0] xor_ln794_2_fu_538_p2;
wire   [0:0] deleted_ones_fu_512_p3;
wire   [0:0] and_ln790_fu_520_p2;
wire   [0:0] and_ln795_fu_550_p2;
wire   [0:0] or_ln795_fu_556_p2;
wire   [0:0] xor_ln795_fu_562_p2;
wire   [0:0] overflow_1_fu_544_p2;
wire   [0:0] underflow_fu_568_p2;
wire   [0:0] or_ln384_fu_582_p2;
wire   [15:0] select_ln384_1_fu_574_p3;
wire   [15:0] val_V_fu_588_p3;
wire  signed [31:0] grp_fu_690_p2;
wire  signed [38:0] sext_ln712_fu_618_p1;
wire  signed [38:0] sext_ln712_1_fu_622_p1;
wire   [38:0] ret_V_fu_628_p2;
wire  signed [37:0] sext_ln1245_fu_625_p1;
wire   [37:0] acc_V_4_fu_642_p2;
wire   [0:0] p_Result_s_fu_634_p3;
wire   [0:0] p_Result_1_fu_648_p3;
wire   [0:0] xor_ln794_fu_656_p2;
wire   [0:0] overflow_fu_662_p2;
wire   [0:0] xor_ln340_fu_668_p2;
wire   [37:0] select_ln384_fu_674_p3;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [0:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire   [31:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire   [0:0] out_stream_TLAST_int_regslice;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg = 1'b0;
end

matVecMul_x_localbuff_V #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
x_localbuff_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_localbuff_V_address0),
    .ce0(x_localbuff_V_ce0),
    .we0(x_localbuff_V_we0),
    .d0(grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_d0),
    .q0(x_localbuff_V_q0)
);

matVecMul_matVecMul_Pipeline_sample_loop grp_matVecMul_Pipeline_sample_loop_fu_261(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start),
    .ap_done(grp_matVecMul_Pipeline_sample_loop_fu_261_ap_done),
    .ap_idle(grp_matVecMul_Pipeline_sample_loop_fu_261_ap_idle),
    .ap_ready(grp_matVecMul_Pipeline_sample_loop_fu_261_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .col_size(col_size_read_reg_705),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_matVecMul_Pipeline_sample_loop_fu_261_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TUSER(in_stream_TUSER_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .in_stream_TID(in_stream_TID_int_regslice),
    .in_stream_TDEST(in_stream_TDEST_int_regslice),
    .x_localbuff_V_address0(grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_address0),
    .x_localbuff_V_ce0(grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_ce0),
    .x_localbuff_V_we0(grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_we0),
    .x_localbuff_V_d0(grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_d0)
);

matVecMul_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .row_size(row_size),
    .col_size(col_size),
    .A_address0(A_address0),
    .A_ce0(A_ce0),
    .A_q0(A_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

matVecMul_mul_mul_16s_16s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16s_16s_32_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(x_localbuff_V_q0),
    .din1(A_q0),
    .ce(1'b1),
    .dout(grp_fu_690_p2)
);

matVecMul_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TLAST_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg <= 1'b1;
        end else if ((grp_matVecMul_Pipeline_sample_loop_fu_261_ap_ready == 1'b1)) begin
            grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        acc_V_3_reg_249 <= acc_V_fu_682_p3;
    end else if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln34_fu_295_p2 == 1'd0))) begin
        acc_V_3_reg_249 <= 38'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_1_fu_166 <= 32'd0;
    end else if ((~((1'b1 == ap_block_state6_io) | ((icmp_ln39_fu_327_p2 == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0))) & (icmp_ln39_fu_327_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        i_1_fu_166 <= add_ln34_reg_728;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        j_reg_238 <= add_ln39_reg_741;
    end else if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln34_fu_295_p2 == 1'd0))) begin
        j_reg_238 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln34_reg_728 <= add_ln34_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state6_io) | ((icmp_ln39_fu_327_p2 == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state6))) begin
        add_ln39_reg_741 <= add_ln39_fu_332_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        col_size_read_reg_705 <= col_size;
        row_size_read_reg_711 <= row_size;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln34_fu_295_p2 == 1'd0))) begin
        shl_ln_reg_733[12 : 7] <= shl_ln_fu_310_p3[12 : 7];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        sub_reg_717 <= sub_fu_287_p2;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_io) | ((icmp_ln39_fu_327_p2 == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state6))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((out_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_matVecMul_Pipeline_sample_loop_fu_261_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state6_io) | ((icmp_ln39_fu_327_p2 == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln34_fu_295_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln34_fu_295_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_matVecMul_Pipeline_sample_loop_fu_261_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((icmp_ln39_fu_327_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_io) | ((icmp_ln39_fu_327_p2 == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0))) & (icmp_ln39_fu_327_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_localbuff_V_address0 = zext_ln39_1_fu_322_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_address0 = grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_address0;
    end else begin
        x_localbuff_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state6_io) | ((icmp_ln39_fu_327_p2 == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_fsm_state6))) begin
        x_localbuff_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_ce0 = grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_ce0;
    end else begin
        x_localbuff_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_we0 = grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_we0;
    end else begin
        x_localbuff_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_matVecMul_Pipeline_sample_loop_fu_261_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln34_fu_295_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5) & (icmp_ln34_fu_295_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if ((~((1'b1 == ap_block_state6_io) | ((icmp_ln39_fu_327_p2 == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0))) & (icmp_ln39_fu_327_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else if ((~((1'b1 == ap_block_state6_io) | ((icmp_ln39_fu_327_p2 == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0))) & (icmp_ln39_fu_327_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state11 : begin
            if (((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_address0 = zext_ln1169_1_fu_377_p1;

assign Range1_all_ones_fu_472_p2 = ((p_Result_8_fu_462_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_478_p2 = ((p_Result_8_fu_462_p4 == 14'd0) ? 1'b1 : 1'b0);

assign Range2_all_ones_fu_456_p2 = ((p_Result_7_fu_446_p4 == 13'd8191) ? 1'b1 : 1'b0);

assign acc_V_4_fu_642_p2 = ($signed(acc_V_3_reg_249) + $signed(sext_ln1245_fu_625_p1));

assign acc_V_fu_682_p3 = ((xor_ln340_fu_668_p2[0:0] == 1'b1) ? select_ln384_fu_674_p3 : acc_V_4_fu_642_p2);

assign add_ln1169_fu_350_p2 = (zext_ln1169_fu_346_p1 + shl_ln_reg_733);

assign add_ln34_fu_300_p2 = (i_1_fu_166 + 32'd1);

assign add_ln39_fu_332_p2 = (j_reg_238 + 7'd1);

assign and_ln789_fu_506_p2 = (xor_ln789_fu_500_p2 & Range2_all_ones_fu_456_p2);

assign and_ln790_fu_520_p2 = (carry_1_fu_440_p2 & Range1_all_ones_fu_472_p2);

assign and_ln795_fu_550_p2 = (p_Result_4_fu_426_p3 & deleted_ones_fu_512_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state6 = ((icmp_ln39_fu_327_p2 == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state6_io = ((icmp_ln39_fu_327_p2 == 1'd1) & (out_stream_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign carry_1_fu_440_p2 = (xor_ln416_fu_434_p2 & p_Result_3_fu_400_p3);

assign deleted_ones_fu_512_p3 = ((carry_1_fu_440_p2[0:0] == 1'b1) ? and_ln789_fu_506_p2 : Range1_all_ones_fu_472_p2);

assign deleted_zeros_fu_484_p3 = ((carry_1_fu_440_p2[0:0] == 1'b1) ? Range1_all_ones_fu_472_p2 : Range1_all_zeros_fu_478_p2);

assign grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start = grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg;

assign icmp_ln34_fu_295_p2 = ((i_1_fu_166 == row_size_read_reg_711) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_327_p2 = ((zext_ln39_fu_318_p1 == col_size_read_reg_705) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign lshr_ln_fu_355_p4 = {{add_ln1169_fu_350_p2[12:7]}};

assign or_ln384_fu_582_p2 = (underflow_fu_568_p2 | overflow_1_fu_544_p2);

assign or_ln794_fu_532_p2 = (xor_ln794_1_fu_526_p2 | p_Result_4_fu_426_p3);

assign or_ln795_fu_556_p2 = (and_ln795_fu_550_p2 | and_ln790_fu_520_p2);

assign out_stream_TDATA_int_regslice = val_V_fu_588_p3;

assign out_stream_TLAST_int_regslice = ((i_1_fu_166 == sub_reg_717) ? 1'b1 : 1'b0);

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign overflow_1_fu_544_p2 = (xor_ln794_2_fu_538_p2 & or_ln794_fu_532_p2);

assign overflow_fu_662_p2 = (xor_ln794_fu_656_p2 & p_Result_1_fu_648_p3);

assign p_Result_1_fu_648_p3 = acc_V_4_fu_642_p2[32'd37];

assign p_Result_2_fu_382_p3 = acc_V_3_reg_249[32'd37];

assign p_Result_3_fu_400_p3 = acc_V_3_reg_249[32'd23];

assign p_Result_4_fu_426_p3 = p_Val2_1_fu_420_p2[32'd15];

assign p_Result_7_fu_446_p4 = {{acc_V_3_reg_249[37:25]}};

assign p_Result_8_fu_462_p4 = {{acc_V_3_reg_249[37:24]}};

assign p_Result_s_fu_634_p3 = ret_V_fu_628_p2[32'd38];

assign p_Val2_1_fu_420_p2 = (zext_ln415_fu_416_p1 + p_Val2_s_fu_390_p4);

assign p_Val2_s_fu_390_p4 = {{acc_V_3_reg_249[23:8]}};

assign ret_V_fu_628_p2 = ($signed(sext_ln712_fu_618_p1) + $signed(sext_ln712_1_fu_622_p1));

assign select_ln384_1_fu_574_p3 = ((overflow_1_fu_544_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln384_fu_674_p3 = ((overflow_fu_662_p2[0:0] == 1'b1) ? 38'd137438953471 : 38'd137438953472);

assign sext_ln1245_fu_625_p1 = grp_fu_690_p2;

assign sext_ln712_1_fu_622_p1 = grp_fu_690_p2;

assign sext_ln712_fu_618_p1 = acc_V_3_reg_249;

assign shl_ln1169_1_fu_338_p3 = {{j_reg_238}, {1'd0}};

assign shl_ln_fu_310_p3 = {{trunc_ln1169_fu_306_p1}, {7'd0}};

assign sub_fu_287_p2 = ($signed(row_size_read_reg_711) + $signed(32'd4294967295));

assign tmp_2_fu_492_p3 = acc_V_3_reg_249[32'd24];

assign tmp_9_fu_369_p3 = {{lshr_ln_fu_355_p4}, {trunc_ln1169_1_fu_365_p1}};

assign tmp_fu_408_p3 = acc_V_3_reg_249[32'd7];

assign trunc_ln1169_1_fu_365_p1 = j_reg_238[5:0];

assign trunc_ln1169_fu_306_p1 = i_1_fu_166[5:0];

assign underflow_fu_568_p2 = (xor_ln795_fu_562_p2 & p_Result_2_fu_382_p3);

assign val_V_fu_588_p3 = ((or_ln384_fu_582_p2[0:0] == 1'b1) ? select_ln384_1_fu_574_p3 : p_Val2_1_fu_420_p2);

assign xor_ln340_fu_668_p2 = (p_Result_s_fu_634_p3 ^ p_Result_1_fu_648_p3);

assign xor_ln416_fu_434_p2 = (p_Result_4_fu_426_p3 ^ 1'd1);

assign xor_ln789_fu_500_p2 = (tmp_2_fu_492_p3 ^ 1'd1);

assign xor_ln794_1_fu_526_p2 = (deleted_zeros_fu_484_p3 ^ 1'd1);

assign xor_ln794_2_fu_538_p2 = (p_Result_2_fu_382_p3 ^ 1'd1);

assign xor_ln794_fu_656_p2 = (p_Result_s_fu_634_p3 ^ 1'd1);

assign xor_ln795_fu_562_p2 = (or_ln795_fu_556_p2 ^ 1'd1);

assign zext_ln1169_1_fu_377_p1 = tmp_9_fu_369_p3;

assign zext_ln1169_fu_346_p1 = shl_ln1169_1_fu_338_p3;

assign zext_ln39_1_fu_322_p1 = j_reg_238;

assign zext_ln39_fu_318_p1 = j_reg_238;

assign zext_ln415_fu_416_p1 = tmp_fu_408_p3;

always @ (posedge ap_clk) begin
    shl_ln_reg_733[6:0] <= 7'b0000000;
end

endmodule //matVecMul
