-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matVecMul_matVecMul_Pipeline_matmul_inner_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    zext_ln32 : IN STD_LOGIC_VECTOR (31 downto 0);
    shl_ln : IN STD_LOGIC_VECTOR (10 downto 0);
    A_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_0_ce0 : OUT STD_LOGIC;
    A_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    A_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_1_ce0 : OUT STD_LOGIC;
    A_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    A_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_2_ce0 : OUT STD_LOGIC;
    A_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    A_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    A_3_ce0 : OUT STD_LOGIC;
    A_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    acc_V_0_out : OUT STD_LOGIC_VECTOR (37 downto 0);
    acc_V_0_out_ap_vld : OUT STD_LOGIC;
    select_ln340_2_out : OUT STD_LOGIC_VECTOR (37 downto 0);
    select_ln340_2_out_ap_vld : OUT STD_LOGIC;
    select_ln340_1_out : OUT STD_LOGIC_VECTOR (37 downto 0);
    select_ln340_1_out_ap_vld : OUT STD_LOGIC;
    select_ln340_out : OUT STD_LOGIC_VECTOR (37 downto 0);
    select_ln340_out_ap_vld : OUT STD_LOGIC;
    x_localbuff_V_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_localbuff_V_3_ce0 : OUT STD_LOGIC;
    x_localbuff_V_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    x_localbuff_V_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_localbuff_V_2_ce0 : OUT STD_LOGIC;
    x_localbuff_V_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    x_localbuff_V_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_localbuff_V_1_ce0 : OUT STD_LOGIC;
    x_localbuff_V_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    x_localbuff_V_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_localbuff_V_0_ce0 : OUT STD_LOGIC;
    x_localbuff_V_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of matVecMul_matVecMul_Pipeline_matmul_inner_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv38_0 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv38_1FFFFFFFFF : STD_LOGIC_VECTOR (37 downto 0) := "01111111111111111111111111111111111111";
    constant ap_const_lv38_2000000000 : STD_LOGIC_VECTOR (37 downto 0) := "10000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal zext_ln32_cast_fu_284_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln32_cast_reg_777 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln52_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_785 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln52_reg_785_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_785_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_785_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_reg_785_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_fu_371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_reg_814 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_reg_814_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_reg_814_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_reg_814_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_1_reg_814_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_2_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_2_reg_823 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_2_reg_823_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_2_reg_823_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_2_reg_823_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_2_reg_823_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_3_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_3_reg_832 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_3_reg_832_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_3_reg_832_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_3_reg_832_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln52_3_reg_832_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_734_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1171_reg_881 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_740_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1171_1_reg_887 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_746_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1171_2_reg_893 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_752_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln1171_3_reg_899 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_V_0_load_reg_905 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal select_ln340_fu_505_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal select_ln340_reg_910 : STD_LOGIC_VECTOR (37 downto 0);
    signal select_ln340_1_fu_577_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal select_ln340_1_reg_915 : STD_LOGIC_VECTOR (37 downto 0);
    signal select_ln340_2_fu_649_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal select_ln340_2_reg_920 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_predicate_tran7to8_state2 : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_phi_mux_UnifiedRetVal_phi_fu_266_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal UnifiedRetVal_reg_262 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal zext_ln1169_fu_349_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln1171_fu_357_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_V_0_fu_110 : STD_LOGIC_VECTOR (37 downto 0);
    signal select_ln340_3_fu_721_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal l_0_fu_114 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln52_fu_398_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1_fu_306_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln1169_fu_316_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal lshr_ln1169_1_fu_321_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln1169_1_fu_331_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_341_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln52_fu_365_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln52_1_fu_376_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln52_2_fu_387_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln712_fu_441_p0 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln712_fu_441_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln712_1_fu_445_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal add_ln1245_fu_451_p2 : STD_LOGIC_VECTOR (38 downto 0);
    signal add_ln712_fu_465_p0 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln1245_fu_448_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln712_fu_465_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal tmp_fu_457_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_471_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln794_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln794_fu_485_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln384_fu_497_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln712_2_fu_513_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln712_3_fu_517_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal add_ln1245_1_fu_523_p2 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln1245_1_fu_520_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln712_1_fu_537_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal tmp_2_fu_529_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_543_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln794_1_fu_551_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln794_1_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_1_fu_563_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln384_1_fu_569_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln712_4_fu_585_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln712_5_fu_589_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal add_ln1245_2_fu_595_p2 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln1245_2_fu_592_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln712_2_fu_609_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal tmp_4_fu_601_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_615_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln794_2_fu_623_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln794_2_fu_629_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_2_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln384_2_fu_641_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln712_6_fu_657_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln712_7_fu_661_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal add_ln1245_3_fu_667_p2 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln1245_3_fu_664_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal add_ln712_3_fu_681_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal tmp_6_fu_673_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_687_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln794_3_fu_695_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln794_3_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_3_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln384_3_fu_713_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_exit_tran_regpp0 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matVecMul_mul_mul_16s_16s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mul_mul_16s_16s_32_4_1_U13 : component matVecMul_mul_mul_16s_16s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_localbuff_V_0_q0,
        din1 => A_0_q0,
        ce => ap_const_logic_1,
        dout => grp_fu_734_p2);

    mul_mul_16s_16s_32_4_1_U14 : component matVecMul_mul_mul_16s_16s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_localbuff_V_1_q0,
        din1 => A_1_q0,
        ce => ap_const_logic_1,
        dout => grp_fu_740_p2);

    mul_mul_16s_16s_32_4_1_U15 : component matVecMul_mul_mul_16s_16s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_localbuff_V_2_q0,
        din1 => A_2_q0,
        ce => ap_const_logic_1,
        dout => grp_fu_746_p2);

    mul_mul_16s_16s_32_4_1_U16 : component matVecMul_mul_mul_16s_16s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => x_localbuff_V_3_q0,
        din1 => A_3_q0,
        ce => ap_const_logic_1,
        dout => grp_fu_752_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv2_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    ap_return_preg <= ap_phi_mux_UnifiedRetVal_phi_fu_266_p8;
                end if; 
            end if;
        end if;
    end process;


    UnifiedRetVal_reg_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_1_reg_814 = ap_const_lv1_1))) then 
                UnifiedRetVal_reg_262 <= ap_const_lv2_3;
            elsif (((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_1) and (icmp_ln52_1_reg_814 = ap_const_lv1_0))) then 
                UnifiedRetVal_reg_262 <= ap_const_lv2_2;
            elsif (((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_0) and (icmp_ln52_1_reg_814 = ap_const_lv1_0))) then 
                UnifiedRetVal_reg_262 <= ap_const_lv2_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                UnifiedRetVal_reg_262 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    acc_V_0_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                acc_V_0_fu_110 <= ap_const_lv38_0;
            elsif (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln52_3_reg_832_pp0_iter4_reg = ap_const_lv1_0) and (icmp_ln52_2_reg_823_pp0_iter4_reg = ap_const_lv1_0) and (icmp_ln52_1_reg_814_pp0_iter4_reg = ap_const_lv1_0) and (icmp_ln52_reg_785_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                acc_V_0_fu_110 <= select_ln340_3_fu_721_p3;
            end if; 
        end if;
    end process;

    ap_exit_tran_regpp0_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                if ((icmp_ln52_fu_301_p2 = ap_const_lv1_1)) then 
                    ap_exit_tran_regpp0(0) <= '1';
                elsif ((ap_predicate_tran7to8_state2 = ap_const_boolean_1)) then 
                    ap_exit_tran_regpp0(0) <= '0';
                end if;
            end if; 
        end if;
    end process;

    l_0_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                l_0_fu_114 <= ap_const_lv64_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln52_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln52_3_fu_393_p2 = ap_const_lv1_0) and (icmp_ln52_2_fu_382_p2 = ap_const_lv1_0) and (icmp_ln52_1_fu_371_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                l_0_fu_114 <= add_ln52_fu_398_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln52_reg_785_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                acc_V_0_load_reg_905 <= acc_V_0_fu_110;
                select_ln340_reg_910 <= select_ln340_fu_505_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln52_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln52_1_reg_814 <= icmp_ln52_1_fu_371_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln52_1_reg_814_pp0_iter1_reg <= icmp_ln52_1_reg_814;
                icmp_ln52_2_reg_823_pp0_iter1_reg <= icmp_ln52_2_reg_823;
                icmp_ln52_3_reg_832_pp0_iter1_reg <= icmp_ln52_3_reg_832;
                icmp_ln52_reg_785_pp0_iter1_reg <= icmp_ln52_reg_785;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln52_1_reg_814_pp0_iter2_reg <= icmp_ln52_1_reg_814_pp0_iter1_reg;
                icmp_ln52_1_reg_814_pp0_iter3_reg <= icmp_ln52_1_reg_814_pp0_iter2_reg;
                icmp_ln52_1_reg_814_pp0_iter4_reg <= icmp_ln52_1_reg_814_pp0_iter3_reg;
                icmp_ln52_2_reg_823_pp0_iter2_reg <= icmp_ln52_2_reg_823_pp0_iter1_reg;
                icmp_ln52_2_reg_823_pp0_iter3_reg <= icmp_ln52_2_reg_823_pp0_iter2_reg;
                icmp_ln52_2_reg_823_pp0_iter4_reg <= icmp_ln52_2_reg_823_pp0_iter3_reg;
                icmp_ln52_3_reg_832_pp0_iter2_reg <= icmp_ln52_3_reg_832_pp0_iter1_reg;
                icmp_ln52_3_reg_832_pp0_iter3_reg <= icmp_ln52_3_reg_832_pp0_iter2_reg;
                icmp_ln52_3_reg_832_pp0_iter4_reg <= icmp_ln52_3_reg_832_pp0_iter3_reg;
                icmp_ln52_reg_785_pp0_iter2_reg <= icmp_ln52_reg_785_pp0_iter1_reg;
                icmp_ln52_reg_785_pp0_iter3_reg <= icmp_ln52_reg_785_pp0_iter2_reg;
                icmp_ln52_reg_785_pp0_iter4_reg <= icmp_ln52_reg_785_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln52_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln52_1_fu_371_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln52_2_reg_823 <= icmp_ln52_2_fu_382_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln52_2_fu_382_p2 = ap_const_lv1_0) and (icmp_ln52_1_fu_371_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln52_3_reg_832 <= icmp_ln52_3_fu_393_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln52_reg_785 <= icmp_ln52_fu_301_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_1_reg_814_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln52_reg_785_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln1171_1_reg_887 <= grp_fu_740_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_2_reg_823_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln52_1_reg_814_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln52_reg_785_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln1171_2_reg_893 <= grp_fu_746_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_3_reg_832_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln52_2_reg_823_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln52_1_reg_814_pp0_iter3_reg = ap_const_lv1_0) and (icmp_ln52_reg_785_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln1171_3_reg_899 <= grp_fu_752_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln52_reg_785_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                mul_ln1171_reg_881 <= grp_fu_734_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln52_1_reg_814_pp0_iter4_reg = ap_const_lv1_0) and (icmp_ln52_reg_785_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln340_1_reg_915 <= select_ln340_1_fu_577_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (icmp_ln52_2_reg_823_pp0_iter4_reg = ap_const_lv1_0) and (icmp_ln52_1_reg_814_pp0_iter4_reg = ap_const_lv1_0) and (icmp_ln52_reg_785_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                select_ln340_2_reg_920 <= select_ln340_2_fu_649_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    zext_ln32_cast_reg_777(31 downto 0) <= zext_ln32_cast_fu_284_p1(31 downto 0);
            end if;
        end if;
    end process;
    zext_ln32_cast_reg_777(63 downto 32) <= "00000000000000000000000000000000";
    ap_exit_tran_regpp0(1) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter4, ap_exit_tran_regpp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_exit_tran_regpp0 = ap_const_lv2_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                elsif (((ap_exit_tran_regpp0 = ap_const_lv2_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    A_0_address0 <= zext_ln1169_fu_349_p1(10 - 1 downto 0);

    A_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_0_ce0 <= ap_const_logic_1;
        else 
            A_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_1_address0 <= zext_ln1169_fu_349_p1(10 - 1 downto 0);

    A_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_1_ce0 <= ap_const_logic_1;
        else 
            A_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_2_address0 <= zext_ln1169_fu_349_p1(10 - 1 downto 0);

    A_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_2_ce0 <= ap_const_logic_1;
        else 
            A_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    A_3_address0 <= zext_ln1169_fu_349_p1(10 - 1 downto 0);

    A_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            A_3_ce0 <= ap_const_logic_1;
        else 
            A_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    acc_V_0_out_assign_proc : process(icmp_ln52_reg_785, icmp_ln52_1_reg_814, icmp_ln52_2_reg_823, acc_V_0_load_reg_905, ap_CS_fsm_state9, ap_CS_fsm_state8, acc_V_0_fu_110)
    begin
        if (((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_1_reg_814 = ap_const_lv1_1))) then 
            acc_V_0_out <= acc_V_0_load_reg_905;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or ((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_1) and (icmp_ln52_1_reg_814 = ap_const_lv1_0)) or ((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_0) and (icmp_ln52_1_reg_814 = ap_const_lv1_0)))) then 
            acc_V_0_out <= acc_V_0_fu_110;
        else 
            acc_V_0_out <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    acc_V_0_out_ap_vld_assign_proc : process(icmp_ln52_reg_785, icmp_ln52_1_reg_814, icmp_ln52_2_reg_823, ap_CS_fsm_state9, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or ((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_1_reg_814 = ap_const_lv1_1)) or ((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_1) and (icmp_ln52_1_reg_814 = ap_const_lv1_0)) or ((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_0) and (icmp_ln52_1_reg_814 = ap_const_lv1_0)))) then 
            acc_V_0_out_ap_vld <= ap_const_logic_1;
        else 
            acc_V_0_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln1169_fu_316_p2 <= std_logic_vector(unsigned(trunc_ln1_fu_306_p4) + unsigned(shl_ln));
    add_ln1245_1_fu_523_p2 <= std_logic_vector(signed(sext_ln712_2_fu_513_p1) + signed(sext_ln712_3_fu_517_p1));
    add_ln1245_2_fu_595_p2 <= std_logic_vector(signed(sext_ln712_4_fu_585_p1) + signed(sext_ln712_5_fu_589_p1));
    add_ln1245_3_fu_667_p2 <= std_logic_vector(signed(sext_ln712_6_fu_657_p1) + signed(sext_ln712_7_fu_661_p1));
    add_ln1245_fu_451_p2 <= std_logic_vector(signed(sext_ln712_fu_441_p1) + signed(sext_ln712_1_fu_445_p1));
    add_ln52_fu_398_p2 <= std_logic_vector(unsigned(l_0_fu_114) + unsigned(ap_const_lv64_4));
    add_ln712_1_fu_537_p2 <= std_logic_vector(signed(select_ln340_fu_505_p3) + signed(sext_ln1245_1_fu_520_p1));
    add_ln712_2_fu_609_p2 <= std_logic_vector(signed(select_ln340_1_fu_577_p3) + signed(sext_ln1245_2_fu_592_p1));
    add_ln712_3_fu_681_p2 <= std_logic_vector(signed(select_ln340_2_fu_649_p3) + signed(sext_ln1245_3_fu_664_p1));
    add_ln712_fu_465_p0 <= acc_V_0_fu_110;
    add_ln712_fu_465_p2 <= std_logic_vector(signed(add_ln712_fu_465_p0) + signed(sext_ln1245_fu_448_p1));
    and_ln794_1_fu_557_p2 <= (xor_ln794_1_fu_551_p2 and tmp_3_fu_543_p3);
    and_ln794_2_fu_629_p2 <= (xor_ln794_2_fu_623_p2 and tmp_5_fu_615_p3);
    and_ln794_3_fu_701_p2 <= (xor_ln794_3_fu_695_p2 and tmp_8_fu_687_p3);
    and_ln794_fu_485_p2 <= (xor_ln794_fu_479_p2 and tmp_1_fu_471_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state8 <= ap_CS_fsm(2);
    ap_CS_fsm_state9 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_flush_enable_assign_proc : process(icmp_ln52_fu_301_p2, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_predicate_tran7to8_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and ((icmp_ln52_fu_301_p2 = ap_const_lv1_1) or (ap_predicate_tran7to8_state2 = ap_const_boolean_1)))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_UnifiedRetVal_phi_fu_266_p8_assign_proc : process(icmp_ln52_reg_785, icmp_ln52_1_reg_814, icmp_ln52_2_reg_823, UnifiedRetVal_reg_262, ap_CS_fsm_state8)
    begin
        if (((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
            if ((icmp_ln52_1_reg_814 = ap_const_lv1_1)) then 
                ap_phi_mux_UnifiedRetVal_phi_fu_266_p8 <= ap_const_lv2_3;
            elsif (((icmp_ln52_2_reg_823 = ap_const_lv1_1) and (icmp_ln52_1_reg_814 = ap_const_lv1_0))) then 
                ap_phi_mux_UnifiedRetVal_phi_fu_266_p8 <= ap_const_lv2_2;
            elsif (((icmp_ln52_2_reg_823 = ap_const_lv1_0) and (icmp_ln52_1_reg_814 = ap_const_lv1_0))) then 
                ap_phi_mux_UnifiedRetVal_phi_fu_266_p8 <= ap_const_lv2_1;
            else 
                ap_phi_mux_UnifiedRetVal_phi_fu_266_p8 <= UnifiedRetVal_reg_262;
            end if;
        else 
            ap_phi_mux_UnifiedRetVal_phi_fu_266_p8 <= UnifiedRetVal_reg_262;
        end if; 
    end process;


    ap_predicate_tran7to8_state2_assign_proc : process(icmp_ln52_fu_301_p2, icmp_ln52_1_fu_371_p2, icmp_ln52_2_fu_382_p2, icmp_ln52_3_fu_393_p2)
    begin
                ap_predicate_tran7to8_state2 <= ((((icmp_ln52_fu_301_p2 = ap_const_lv1_0) and (icmp_ln52_2_fu_382_p2 = ap_const_lv1_1)) or ((icmp_ln52_fu_301_p2 = ap_const_lv1_0) and (icmp_ln52_3_fu_393_p2 = ap_const_lv1_1))) or ((icmp_ln52_fu_301_p2 = ap_const_lv1_0) and (icmp_ln52_1_fu_371_p2 = ap_const_lv1_1)));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_UnifiedRetVal_phi_fu_266_p8, ap_CS_fsm_state8, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_return <= ap_phi_mux_UnifiedRetVal_phi_fu_266_p8;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    icmp_ln52_1_fu_371_p2 <= "1" when (or_ln52_fu_365_p2 = zext_ln32_cast_reg_777) else "0";
    icmp_ln52_2_fu_382_p2 <= "1" when (or_ln52_1_fu_376_p2 = zext_ln32_cast_reg_777) else "0";
    icmp_ln52_3_fu_393_p2 <= "1" when (or_ln52_2_fu_387_p2 = zext_ln32_cast_reg_777) else "0";
    icmp_ln52_fu_301_p2 <= "1" when (l_0_fu_114 = zext_ln32_cast_reg_777) else "0";
    lshr_ln1169_1_fu_321_p4 <= add_ln1169_fu_316_p2(10 downto 5);
    or_ln52_1_fu_376_p2 <= (l_0_fu_114 or ap_const_lv64_2);
    or_ln52_2_fu_387_p2 <= (l_0_fu_114 or ap_const_lv64_3);
    or_ln52_fu_365_p2 <= (l_0_fu_114 or ap_const_lv64_1);
    select_ln340_1_fu_577_p3 <= 
        select_ln384_1_fu_569_p3 when (xor_ln340_1_fu_563_p2(0) = '1') else 
        add_ln712_1_fu_537_p2;
    select_ln340_1_out <= select_ln340_1_reg_915;

    select_ln340_1_out_ap_vld_assign_proc : process(icmp_ln52_reg_785, icmp_ln52_1_reg_814, icmp_ln52_2_reg_823, ap_CS_fsm_state8)
    begin
        if ((((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_1) and (icmp_ln52_1_reg_814 = ap_const_lv1_0)) or ((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_0) and (icmp_ln52_1_reg_814 = ap_const_lv1_0)))) then 
            select_ln340_1_out_ap_vld <= ap_const_logic_1;
        else 
            select_ln340_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln340_2_fu_649_p3 <= 
        select_ln384_2_fu_641_p3 when (xor_ln340_2_fu_635_p2(0) = '1') else 
        add_ln712_2_fu_609_p2;
    select_ln340_2_out <= select_ln340_2_reg_920;

    select_ln340_2_out_ap_vld_assign_proc : process(icmp_ln52_reg_785, icmp_ln52_1_reg_814, icmp_ln52_2_reg_823, ap_CS_fsm_state8)
    begin
        if (((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_0) and (icmp_ln52_1_reg_814 = ap_const_lv1_0))) then 
            select_ln340_2_out_ap_vld <= ap_const_logic_1;
        else 
            select_ln340_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln340_3_fu_721_p3 <= 
        select_ln384_3_fu_713_p3 when (xor_ln340_3_fu_707_p2(0) = '1') else 
        add_ln712_3_fu_681_p2;
    select_ln340_fu_505_p3 <= 
        select_ln384_fu_497_p3 when (xor_ln340_fu_491_p2(0) = '1') else 
        add_ln712_fu_465_p2;
    select_ln340_out <= select_ln340_reg_910;

    select_ln340_out_ap_vld_assign_proc : process(icmp_ln52_reg_785, icmp_ln52_1_reg_814, icmp_ln52_2_reg_823, ap_CS_fsm_state8)
    begin
        if ((((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_1_reg_814 = ap_const_lv1_1)) or ((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_1) and (icmp_ln52_1_reg_814 = ap_const_lv1_0)) or ((icmp_ln52_reg_785 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln52_2_reg_823 = ap_const_lv1_0) and (icmp_ln52_1_reg_814 = ap_const_lv1_0)))) then 
            select_ln340_out_ap_vld <= ap_const_logic_1;
        else 
            select_ln340_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln384_1_fu_569_p3 <= 
        ap_const_lv38_1FFFFFFFFF when (and_ln794_1_fu_557_p2(0) = '1') else 
        ap_const_lv38_2000000000;
    select_ln384_2_fu_641_p3 <= 
        ap_const_lv38_1FFFFFFFFF when (and_ln794_2_fu_629_p2(0) = '1') else 
        ap_const_lv38_2000000000;
    select_ln384_3_fu_713_p3 <= 
        ap_const_lv38_1FFFFFFFFF when (and_ln794_3_fu_701_p2(0) = '1') else 
        ap_const_lv38_2000000000;
    select_ln384_fu_497_p3 <= 
        ap_const_lv38_1FFFFFFFFF when (and_ln794_fu_485_p2(0) = '1') else 
        ap_const_lv38_2000000000;
        sext_ln1245_1_fu_520_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln1171_1_reg_887),38));

        sext_ln1245_2_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln1171_2_reg_893),38));

        sext_ln1245_3_fu_664_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln1171_3_reg_899),38));

        sext_ln1245_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln1171_reg_881),38));

        sext_ln712_1_fu_445_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln1171_reg_881),39));

        sext_ln712_2_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_fu_505_p3),39));

        sext_ln712_3_fu_517_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln1171_1_reg_887),39));

        sext_ln712_4_fu_585_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_1_fu_577_p3),39));

        sext_ln712_5_fu_589_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln1171_2_reg_893),39));

        sext_ln712_6_fu_657_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln340_2_fu_649_p3),39));

        sext_ln712_7_fu_661_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln1171_3_reg_899),39));

    sext_ln712_fu_441_p0 <= acc_V_0_fu_110;
        sext_ln712_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln712_fu_441_p0),39));

    tmp_1_fu_471_p3 <= add_ln712_fu_465_p2(37 downto 37);
    tmp_2_fu_529_p3 <= add_ln1245_1_fu_523_p2(38 downto 38);
    tmp_3_fu_543_p3 <= add_ln712_1_fu_537_p2(37 downto 37);
    tmp_4_fu_601_p3 <= add_ln1245_2_fu_595_p2(38 downto 38);
    tmp_5_fu_615_p3 <= add_ln712_2_fu_609_p2(37 downto 37);
    tmp_6_fu_673_p3 <= add_ln1245_3_fu_667_p2(38 downto 38);
    tmp_7_fu_341_p3 <= (lshr_ln1169_1_fu_321_p4 & trunc_ln1169_1_fu_331_p4);
    tmp_8_fu_687_p3 <= add_ln712_3_fu_681_p2(37 downto 37);
    tmp_fu_457_p3 <= add_ln1245_fu_451_p2(38 downto 38);
    trunc_ln1169_1_fu_331_p4 <= l_0_fu_114(5 downto 2);
    trunc_ln1_fu_306_p4 <= l_0_fu_114(11 downto 1);
    x_localbuff_V_0_address0 <= zext_ln1171_fu_357_p1(4 - 1 downto 0);

    x_localbuff_V_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            x_localbuff_V_0_ce0 <= ap_const_logic_1;
        else 
            x_localbuff_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_localbuff_V_1_address0 <= zext_ln1171_fu_357_p1(4 - 1 downto 0);

    x_localbuff_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            x_localbuff_V_1_ce0 <= ap_const_logic_1;
        else 
            x_localbuff_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_localbuff_V_2_address0 <= zext_ln1171_fu_357_p1(4 - 1 downto 0);

    x_localbuff_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            x_localbuff_V_2_ce0 <= ap_const_logic_1;
        else 
            x_localbuff_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_localbuff_V_3_address0 <= zext_ln1171_fu_357_p1(4 - 1 downto 0);

    x_localbuff_V_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            x_localbuff_V_3_ce0 <= ap_const_logic_1;
        else 
            x_localbuff_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln340_1_fu_563_p2 <= (tmp_3_fu_543_p3 xor tmp_2_fu_529_p3);
    xor_ln340_2_fu_635_p2 <= (tmp_5_fu_615_p3 xor tmp_4_fu_601_p3);
    xor_ln340_3_fu_707_p2 <= (tmp_8_fu_687_p3 xor tmp_6_fu_673_p3);
    xor_ln340_fu_491_p2 <= (tmp_fu_457_p3 xor tmp_1_fu_471_p3);
    xor_ln794_1_fu_551_p2 <= (tmp_2_fu_529_p3 xor ap_const_lv1_1);
    xor_ln794_2_fu_623_p2 <= (tmp_4_fu_601_p3 xor ap_const_lv1_1);
    xor_ln794_3_fu_695_p2 <= (tmp_6_fu_673_p3 xor ap_const_lv1_1);
    xor_ln794_fu_479_p2 <= (tmp_fu_457_p3 xor ap_const_lv1_1);
    zext_ln1169_fu_349_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_341_p3),64));
    zext_ln1171_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln1169_1_fu_331_p4),64));
    zext_ln32_cast_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln32),64));
end behav;
