#!/usr/bin/env python3
"""
Generate FIR coefficients, input samples, and reference output for Lab 2.

Filter design follows the course example in slides/code/fir_design.py:
  - window method via scipy.signal.firwin
  - low-pass FIR with Hamming window
"""

from pathlib import Path

import numpy as np


FS_HZ = 1000.0
FC_HZ = 100.0
N_TAPS = 51
N_SAMPLES = 128


def write_float_vector(path: Path, values: np.ndarray) -> None:
    with path.open("w", encoding="utf-8") as file_obj:
        for value in values:
            file_obj.write(f"{value:.9f}\n")


def write_coeff_header(path: Path, coeffs: np.ndarray) -> None:
    with path.open("w", encoding="utf-8") as file_obj:
        file_obj.write("// Auto-generated by generate_fir_test_vectors.py\n")
        file_obj.write(f"#define N_TAPS {N_TAPS}\n\n")
        file_obj.write("static const float fir_coeffs[N_TAPS] = {\n")
        for index, value in enumerate(coeffs):
            trailing = "," if index < N_TAPS - 1 else ""
            file_obj.write(f"    {value:.9f}f{trailing}\n")
        file_obj.write("};\n")


def main() -> None:
    root = Path(__file__).resolve().parent

    n = np.arange(N_TAPS, dtype=np.float64)
    center = (N_TAPS - 1) / 2.0
    cutoff_norm = FC_HZ / FS_HZ

    coeffs = 2.0 * cutoff_norm * np.sinc(2.0 * cutoff_norm * (n - center))
    coeffs *= np.hamming(N_TAPS)
    coeffs /= np.sum(coeffs)

    sample_index = np.arange(N_SAMPLES, dtype=np.float64)
    x = (
        0.7 * np.sin(2.0 * np.pi * 50.0 * sample_index / FS_HZ)
        + 0.3 * np.sin(2.0 * np.pi * 300.0 * sample_index / FS_HZ)
    )
    x[0] += 1.0

    y_ref = np.convolve(x, coeffs, mode="full")[:N_SAMPLES]

    write_coeff_header(root / "fir_coeffs.h", coeffs)
    write_float_vector(root / "input.txt", x)
    write_float_vector(root / "expected_output.txt", y_ref)

    print("Generated:")
    print("  fir_coeffs.h")
    print("  input.txt")
    print("  expected_output.txt")


if __name__ == "__main__":
    main()
