-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matVecMul_matVecMul_Pipeline_sample_loop is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    col_size : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    x_localbuff_V_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_localbuff_V_0_ce0 : OUT STD_LOGIC;
    x_localbuff_V_0_we0 : OUT STD_LOGIC;
    x_localbuff_V_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    x_localbuff_V_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_localbuff_V_1_ce0 : OUT STD_LOGIC;
    x_localbuff_V_1_we0 : OUT STD_LOGIC;
    x_localbuff_V_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    x_localbuff_V_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_localbuff_V_2_ce0 : OUT STD_LOGIC;
    x_localbuff_V_2_we0 : OUT STD_LOGIC;
    x_localbuff_V_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    x_localbuff_V_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    x_localbuff_V_3_ce0 : OUT STD_LOGIC;
    x_localbuff_V_3_we0 : OUT STD_LOGIC;
    x_localbuff_V_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of matVecMul_matVecMul_Pipeline_sample_loop is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln35_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal zext_ln40_fu_190_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_64 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln35_fu_158_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln40_fu_176_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_Result_s_fu_168_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln_fu_180_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_170 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matVecMul_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component matVecMul_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    j_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_170)) then
                if ((icmp_ln35_fu_152_p2 = ap_const_lv1_0)) then 
                    j_fu_64 <= add_ln35_fu_158_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_64 <= ap_const_lv32_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln35_fu_158_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_j_1) + unsigned(ap_const_lv32_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)));
    end process;


    ap_condition_170_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
                ap_condition_170 <= (not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln35_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j_1_assign_proc : process(ap_CS_fsm_state1, j_fu_64, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_j_1 <= ap_const_lv32_0;
        else 
            ap_sig_allocacmp_j_1 <= j_fu_64;
        end if; 
    end process;

    icmp_ln35_fu_152_p2 <= "1" when (ap_sig_allocacmp_j_1 = col_size) else "0";

    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
        if (((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    in_stream_TREADY_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            in_stream_TREADY <= ap_const_logic_1;
        else 
            in_stream_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln_fu_180_p4 <= ap_sig_allocacmp_j_1(5 downto 2);
    p_Result_s_fu_168_p1 <= in_stream_TDATA(16 - 1 downto 0);
    trunc_ln40_fu_176_p1 <= ap_sig_allocacmp_j_1(2 - 1 downto 0);
    x_localbuff_V_0_address0 <= zext_ln40_fu_190_p1(4 - 1 downto 0);

    x_localbuff_V_0_ce0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_localbuff_V_0_ce0 <= ap_const_logic_1;
        else 
            x_localbuff_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_localbuff_V_0_d0 <= p_Result_s_fu_168_p1;

    x_localbuff_V_0_we0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, trunc_ln40_fu_176_p1, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln40_fu_176_p1 = ap_const_lv2_0))) then 
            x_localbuff_V_0_we0 <= ap_const_logic_1;
        else 
            x_localbuff_V_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_localbuff_V_1_address0 <= zext_ln40_fu_190_p1(4 - 1 downto 0);

    x_localbuff_V_1_ce0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_localbuff_V_1_ce0 <= ap_const_logic_1;
        else 
            x_localbuff_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_localbuff_V_1_d0 <= p_Result_s_fu_168_p1;

    x_localbuff_V_1_we0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, trunc_ln40_fu_176_p1, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln40_fu_176_p1 = ap_const_lv2_1))) then 
            x_localbuff_V_1_we0 <= ap_const_logic_1;
        else 
            x_localbuff_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_localbuff_V_2_address0 <= zext_ln40_fu_190_p1(4 - 1 downto 0);

    x_localbuff_V_2_ce0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_localbuff_V_2_ce0 <= ap_const_logic_1;
        else 
            x_localbuff_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_localbuff_V_2_d0 <= p_Result_s_fu_168_p1;

    x_localbuff_V_2_we0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, trunc_ln40_fu_176_p1, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln40_fu_176_p1 = ap_const_lv2_2))) then 
            x_localbuff_V_2_we0 <= ap_const_logic_1;
        else 
            x_localbuff_V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_localbuff_V_3_address0 <= zext_ln40_fu_190_p1(4 - 1 downto 0);

    x_localbuff_V_3_ce0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_localbuff_V_3_ce0 <= ap_const_logic_1;
        else 
            x_localbuff_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_localbuff_V_3_d0 <= p_Result_s_fu_168_p1;

    x_localbuff_V_3_we0_assign_proc : process(ap_CS_fsm_state1, in_stream_TVALID, icmp_ln35_fu_152_p2, trunc_ln40_fu_176_p1, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (in_stream_TVALID = ap_const_logic_0)))) and (icmp_ln35_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (trunc_ln40_fu_176_p1 = ap_const_lv2_3))) then 
            x_localbuff_V_3_we0 <= ap_const_logic_1;
        else 
            x_localbuff_V_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln40_fu_190_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_180_p4),64));
end behav;
