// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matVecMul_matVecMul,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=18.153000,HLS_SYN_LAT=1863,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1765,HLS_SYN_LUT=2510,HLS_VERSION=2021_1}" *)

module matVecMul (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TUSER,
        out_stream_TLAST,
        out_stream_TID,
        out_stream_TDEST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 14;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [31:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [3:0] out_stream_TKEEP;
output  [3:0] out_stream_TSTRB;
output  [0:0] out_stream_TUSER;
output  [0:0] out_stream_TLAST;
output  [0:0] out_stream_TID;
output  [0:0] out_stream_TDEST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] A_0_q0;
wire   [15:0] A_1_q0;
wire   [15:0] A_2_q0;
wire   [15:0] A_3_q0;
wire   [31:0] no_of_vectors;
wire   [31:0] row_size;
wire   [31:0] col_size;
reg   [3:0] x_localbuff_V_0_address0;
reg    x_localbuff_V_0_ce0;
reg    x_localbuff_V_0_we0;
wire   [15:0] x_localbuff_V_0_q0;
reg   [3:0] x_localbuff_V_1_address0;
reg    x_localbuff_V_1_ce0;
reg    x_localbuff_V_1_we0;
wire   [15:0] x_localbuff_V_1_q0;
reg   [3:0] x_localbuff_V_2_address0;
reg    x_localbuff_V_2_ce0;
reg    x_localbuff_V_2_we0;
wire   [15:0] x_localbuff_V_2_q0;
reg   [3:0] x_localbuff_V_3_address0;
reg    x_localbuff_V_3_ce0;
reg    x_localbuff_V_3_we0;
wire   [15:0] x_localbuff_V_3_q0;
reg    out_stream_TDATA_blk_n;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [31:0] col_size_read_reg_614;
reg   [31:0] row_size_read_reg_620;
reg   [31:0] no_of_vectors_read_reg_625;
wire   [31:0] sub_fu_304_p2;
reg   [31:0] sub_reg_654;
wire   [30:0] add_ln32_fu_327_p2;
reg   [30:0] add_ln32_reg_662;
wire    ap_CS_fsm_state2;
wire   [31:0] add_ln44_fu_338_p2;
reg   [31:0] add_ln44_reg_670;
wire    ap_CS_fsm_state5;
wire   [10:0] shl_ln_fu_348_p3;
reg   [10:0] shl_ln_reg_675;
wire   [0:0] icmp_ln44_fu_333_p2;
wire   [0:0] out_pkt_last_V_fu_357_p2;
reg   [0:0] out_pkt_last_V_reg_680;
wire   [1:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_return;
reg   [1:0] targetBlock_reg_685;
wire    ap_CS_fsm_state6;
wire   [15:0] p_Val2_1_fu_429_p2;
reg   [15:0] p_Val2_1_reg_690;
wire    ap_CS_fsm_state7;
wire   [0:0] overflow_fu_553_p2;
reg   [0:0] overflow_reg_695;
wire   [0:0] or_ln384_fu_583_p2;
reg   [0:0] or_ln384_reg_700;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_ap_done;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_ap_idle;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_ap_ready;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_in_stream_TREADY;
wire   [3:0] grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_address0;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_ce0;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_we0;
wire   [15:0] grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_d0;
wire   [3:0] grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_address0;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_ce0;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_we0;
wire   [15:0] grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_d0;
wire   [3:0] grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_address0;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_ce0;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_we0;
wire   [15:0] grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_d0;
wire   [3:0] grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_address0;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_ce0;
wire    grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_we0;
wire   [15:0] grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_d0;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_done;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_idle;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_ready;
wire   [9:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_address0;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_ce0;
wire   [9:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_address0;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_ce0;
wire   [9:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_address0;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_ce0;
wire   [9:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_address0;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_ce0;
wire   [37:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out_ap_vld;
wire   [37:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out_ap_vld;
wire   [37:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out_ap_vld;
wire   [37:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out_ap_vld;
wire   [3:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_address0;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_ce0;
wire   [3:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_address0;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_ce0;
wire   [3:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_address0;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_ce0;
wire   [3:0] grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_address0;
wire    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_ce0;
reg   [31:0] k_reg_240;
wire    ap_CS_fsm_state4;
reg    grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
wire   [0:0] icmp_ln32_fu_322_p2;
wire    ap_CS_fsm_state3;
reg    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg;
reg   [37:0] acc_V_0_loc_fu_188;
reg   [37:0] select_ln340_2_loc_fu_184;
reg   [37:0] select_ln340_1_loc_fu_180;
reg   [37:0] select_ln340_loc_fu_176;
reg   [30:0] i_fu_172;
wire   [31:0] zext_ln32_fu_318_p1;
wire   [5:0] trunc_ln1169_fu_344_p1;
wire   [37:0] acc_V_lcssa_fu_378_p6;
wire   [0:0] tmp_fu_417_p3;
wire   [15:0] zext_ln415_fu_425_p1;
wire   [15:0] p_Val2_s_fu_399_p4;
wire   [0:0] p_Result_2_fu_435_p3;
wire   [0:0] p_Result_1_fu_409_p3;
wire   [0:0] xor_ln416_fu_443_p2;
wire   [12:0] p_Result_7_fu_455_p4;
wire   [13:0] p_Result_8_fu_471_p4;
wire   [0:0] carry_1_fu_449_p2;
wire   [0:0] Range1_all_ones_fu_481_p2;
wire   [0:0] Range1_all_zeros_fu_487_p2;
wire   [0:0] tmp_10_fu_501_p3;
wire   [0:0] Range2_all_ones_fu_465_p2;
wire   [0:0] xor_ln789_fu_509_p2;
wire   [0:0] and_ln789_fu_515_p2;
wire   [0:0] deleted_zeros_fu_493_p3;
wire   [0:0] xor_ln794_fu_535_p2;
wire   [0:0] p_Result_s_fu_391_p3;
wire   [0:0] or_ln794_fu_541_p2;
wire   [0:0] xor_ln794_1_fu_547_p2;
wire   [0:0] deleted_ones_fu_521_p3;
wire   [0:0] and_ln790_fu_529_p2;
wire   [0:0] and_ln795_fu_559_p2;
wire   [0:0] or_ln795_fu_565_p2;
wire   [0:0] xor_ln795_fu_571_p2;
wire   [0:0] underflow_fu_577_p2;
wire   [15:0] select_ln384_fu_589_p3;
wire   [15:0] val_V_fu_596_p3;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [0:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire   [31:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_user_V_U_apdone_blk;
wire    regslice_both_out_stream_V_user_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_user_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    regslice_both_out_stream_V_id_V_U_apdone_blk;
wire    regslice_both_out_stream_V_id_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_id_V_U_vld_out;
wire    regslice_both_out_stream_V_dest_V_U_apdone_blk;
wire    regslice_both_out_stream_V_dest_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg = 1'b0;
#0 grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg = 1'b0;
end

matVecMul_x_localbuff_V_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
x_localbuff_V_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_localbuff_V_0_address0),
    .ce0(x_localbuff_V_0_ce0),
    .we0(x_localbuff_V_0_we0),
    .d0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_d0),
    .q0(x_localbuff_V_0_q0)
);

matVecMul_x_localbuff_V_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
x_localbuff_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_localbuff_V_1_address0),
    .ce0(x_localbuff_V_1_ce0),
    .we0(x_localbuff_V_1_we0),
    .d0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_d0),
    .q0(x_localbuff_V_1_q0)
);

matVecMul_x_localbuff_V_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
x_localbuff_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_localbuff_V_2_address0),
    .ce0(x_localbuff_V_2_ce0),
    .we0(x_localbuff_V_2_we0),
    .d0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_d0),
    .q0(x_localbuff_V_2_q0)
);

matVecMul_x_localbuff_V_0 #(
    .DataWidth( 16 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
x_localbuff_V_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(x_localbuff_V_3_address0),
    .ce0(x_localbuff_V_3_ce0),
    .we0(x_localbuff_V_3_we0),
    .d0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_d0),
    .q0(x_localbuff_V_3_q0)
);

matVecMul_matVecMul_Pipeline_sample_loop grp_matVecMul_Pipeline_sample_loop_fu_251(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start),
    .ap_done(grp_matVecMul_Pipeline_sample_loop_fu_251_ap_done),
    .ap_idle(grp_matVecMul_Pipeline_sample_loop_fu_251_ap_idle),
    .ap_ready(grp_matVecMul_Pipeline_sample_loop_fu_251_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .col_size(col_size_read_reg_614),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_matVecMul_Pipeline_sample_loop_fu_251_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TUSER(in_stream_TUSER_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .in_stream_TID(in_stream_TID_int_regslice),
    .in_stream_TDEST(in_stream_TDEST_int_regslice),
    .x_localbuff_V_0_address0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_address0),
    .x_localbuff_V_0_ce0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_ce0),
    .x_localbuff_V_0_we0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_we0),
    .x_localbuff_V_0_d0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_d0),
    .x_localbuff_V_1_address0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_address0),
    .x_localbuff_V_1_ce0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_ce0),
    .x_localbuff_V_1_we0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_we0),
    .x_localbuff_V_1_d0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_d0),
    .x_localbuff_V_2_address0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_address0),
    .x_localbuff_V_2_ce0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_ce0),
    .x_localbuff_V_2_we0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_we0),
    .x_localbuff_V_2_d0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_d0),
    .x_localbuff_V_3_address0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_address0),
    .x_localbuff_V_3_ce0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_ce0),
    .x_localbuff_V_3_we0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_we0),
    .x_localbuff_V_3_d0(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_d0)
);

matVecMul_matVecMul_Pipeline_matmul_inner_loop grp_matVecMul_Pipeline_matmul_inner_loop_fu_278(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start),
    .ap_done(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_done),
    .ap_idle(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_idle),
    .ap_ready(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_ready),
    .zext_ln32(col_size_read_reg_614),
    .shl_ln(shl_ln_reg_675),
    .A_0_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_address0),
    .A_0_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_ce0),
    .A_0_q0(A_0_q0),
    .A_1_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_address0),
    .A_1_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_ce0),
    .A_1_q0(A_1_q0),
    .A_2_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_address0),
    .A_2_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_ce0),
    .A_2_q0(A_2_q0),
    .A_3_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_address0),
    .A_3_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_ce0),
    .A_3_q0(A_3_q0),
    .acc_V_0_out(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out),
    .acc_V_0_out_ap_vld(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out_ap_vld),
    .select_ln340_2_out(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out),
    .select_ln340_2_out_ap_vld(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out_ap_vld),
    .select_ln340_1_out(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out),
    .select_ln340_1_out_ap_vld(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out_ap_vld),
    .select_ln340_out(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out),
    .select_ln340_out_ap_vld(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out_ap_vld),
    .x_localbuff_V_3_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_address0),
    .x_localbuff_V_3_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_ce0),
    .x_localbuff_V_3_q0(x_localbuff_V_3_q0),
    .x_localbuff_V_2_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_address0),
    .x_localbuff_V_2_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_ce0),
    .x_localbuff_V_2_q0(x_localbuff_V_2_q0),
    .x_localbuff_V_1_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_address0),
    .x_localbuff_V_1_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_ce0),
    .x_localbuff_V_1_q0(x_localbuff_V_1_q0),
    .x_localbuff_V_0_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_address0),
    .x_localbuff_V_0_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_ce0),
    .x_localbuff_V_0_q0(x_localbuff_V_0_q0),
    .ap_return(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_return)
);

matVecMul_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .no_of_vectors(no_of_vectors),
    .row_size(row_size),
    .col_size(col_size),
    .A_0_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_address0),
    .A_0_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_ce0),
    .A_0_q0(A_0_q0),
    .A_1_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_address0),
    .A_1_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_ce0),
    .A_1_q0(A_1_q0),
    .A_2_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_address0),
    .A_2_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_ce0),
    .A_2_q0(A_2_q0),
    .A_3_address0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_address0),
    .A_3_ce0(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_ce0),
    .A_3_q0(A_3_q0),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

matVecMul_mux_42_38_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 38 ),
    .din1_WIDTH( 38 ),
    .din2_WIDTH( 38 ),
    .din3_WIDTH( 38 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 38 ))
mux_42_38_1_1_U32(
    .din0(acc_V_0_loc_fu_188),
    .din1(select_ln340_2_loc_fu_184),
    .din2(select_ln340_1_loc_fu_180),
    .din3(select_ln340_loc_fu_176),
    .din4(targetBlock_reg_685),
    .dout(acc_V_lcssa_fu_378_p6)
);

matVecMul_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_user_V_U_ack_in_dummy),
    .data_out(out_stream_TUSER),
    .vld_out(regslice_both_out_stream_V_user_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_user_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_pkt_last_V_reg_680),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_id_V_U_ack_in_dummy),
    .data_out(out_stream_TID),
    .vld_out(regslice_both_out_stream_V_id_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_id_V_U_apdone_blk)
);

matVecMul_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_dest_V_U_ack_in_dummy),
    .data_out(out_stream_TDEST),
    .vld_out(regslice_both_out_stream_V_dest_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln44_fu_333_p2 == 1'd0))) begin
            grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg <= 1'b1;
        end else if ((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_ready == 1'b1)) begin
            grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln32_fu_322_p2 == 1'd1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg <= 1'b1;
        end else if ((grp_matVecMul_Pipeline_sample_loop_fu_251_ap_ready == 1'b1)) begin
            grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_172 <= 31'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln44_fu_333_p2 == 1'd1))) begin
        i_fu_172 <= add_ln32_reg_662;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        k_reg_240 <= 32'd0;
    end else if (((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        k_reg_240 <= add_ln44_reg_670;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        acc_V_0_loc_fu_188 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln32_reg_662 <= add_ln32_fu_327_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln44_reg_670 <= add_ln44_fu_338_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        col_size_read_reg_614 <= col_size;
        no_of_vectors_read_reg_625 <= no_of_vectors;
        row_size_read_reg_620 <= row_size;
        sub_reg_654 <= sub_fu_304_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        or_ln384_reg_700 <= or_ln384_fu_583_p2;
        overflow_reg_695 <= overflow_fu_553_p2;
        p_Val2_1_reg_690 <= p_Val2_1_fu_429_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln44_fu_333_p2 == 1'd0))) begin
        out_pkt_last_V_reg_680 <= out_pkt_last_V_fu_357_p2;
        shl_ln_reg_675[10 : 5] <= shl_ln_fu_348_p3[10 : 5];
    end
end

always @ (posedge ap_clk) begin
    if (((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        select_ln340_1_loc_fu_180 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        select_ln340_2_loc_fu_184 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        select_ln340_loc_fu_176 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        targetBlock_reg_685 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_return;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_matVecMul_Pipeline_sample_loop_fu_251_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((out_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((out_stream_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_322_p2 == 1'd0) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln32_fu_322_p2 == 1'd0) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_matVecMul_Pipeline_sample_loop_fu_251_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_localbuff_V_0_address0 = grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_0_address0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_address0;
    end else begin
        x_localbuff_V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_localbuff_V_0_ce0 = grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_0_ce0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_ce0;
    end else begin
        x_localbuff_V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_0_we0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_we0;
    end else begin
        x_localbuff_V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_localbuff_V_1_address0 = grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_1_address0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_address0;
    end else begin
        x_localbuff_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_localbuff_V_1_ce0 = grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_1_ce0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_ce0;
    end else begin
        x_localbuff_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_1_we0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_we0;
    end else begin
        x_localbuff_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_localbuff_V_2_address0 = grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_2_address0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_address0;
    end else begin
        x_localbuff_V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_localbuff_V_2_ce0 = grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_2_ce0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_ce0;
    end else begin
        x_localbuff_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_2_we0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_we0;
    end else begin
        x_localbuff_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_localbuff_V_3_address0 = grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_3_address0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_address0;
    end else begin
        x_localbuff_V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_localbuff_V_3_ce0 = grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_3_ce0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_ce0;
    end else begin
        x_localbuff_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        x_localbuff_V_3_we0 = grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_we0;
    end else begin
        x_localbuff_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln32_fu_322_p2 == 1'd0) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln32_fu_322_p2 == 1'd1) & (regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_matVecMul_Pipeline_sample_loop_fu_251_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln44_fu_333_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((out_stream_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Range1_all_ones_fu_481_p2 = ((p_Result_8_fu_471_p4 == 14'd16383) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_487_p2 = ((p_Result_8_fu_471_p4 == 14'd0) ? 1'b1 : 1'b0);

assign Range2_all_ones_fu_465_p2 = ((p_Result_7_fu_455_p4 == 13'd8191) ? 1'b1 : 1'b0);

assign add_ln32_fu_327_p2 = (i_fu_172 + 31'd1);

assign add_ln44_fu_338_p2 = (k_reg_240 + 32'd1);

assign and_ln789_fu_515_p2 = (xor_ln789_fu_509_p2 & Range2_all_ones_fu_465_p2);

assign and_ln790_fu_529_p2 = (carry_1_fu_449_p2 & Range1_all_ones_fu_481_p2);

assign and_ln795_fu_559_p2 = (p_Result_2_fu_435_p3 & deleted_ones_fu_521_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign carry_1_fu_449_p2 = (xor_ln416_fu_443_p2 & p_Result_1_fu_409_p3);

assign deleted_ones_fu_521_p3 = ((carry_1_fu_449_p2[0:0] == 1'b1) ? and_ln789_fu_515_p2 : Range1_all_ones_fu_481_p2);

assign deleted_zeros_fu_493_p3 = ((carry_1_fu_449_p2[0:0] == 1'b1) ? Range1_all_ones_fu_481_p2 : Range1_all_zeros_fu_487_p2);

assign grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start = grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg;

assign grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start = grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg;

assign icmp_ln32_fu_322_p2 = (($signed(zext_ln32_fu_318_p1) < $signed(no_of_vectors_read_reg_625)) ? 1'b1 : 1'b0);

assign icmp_ln44_fu_333_p2 = ((k_reg_240 == row_size_read_reg_620) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign or_ln384_fu_583_p2 = (underflow_fu_577_p2 | overflow_fu_553_p2);

assign or_ln794_fu_541_p2 = (xor_ln794_fu_535_p2 | p_Result_2_fu_435_p3);

assign or_ln795_fu_565_p2 = (and_ln795_fu_559_p2 | and_ln790_fu_529_p2);

assign out_pkt_last_V_fu_357_p2 = ((k_reg_240 == sub_reg_654) ? 1'b1 : 1'b0);

assign out_stream_TDATA_int_regslice = val_V_fu_596_p3;

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign overflow_fu_553_p2 = (xor_ln794_1_fu_547_p2 & or_ln794_fu_541_p2);

assign p_Result_1_fu_409_p3 = acc_V_lcssa_fu_378_p6[32'd23];

assign p_Result_2_fu_435_p3 = p_Val2_1_fu_429_p2[32'd15];

assign p_Result_7_fu_455_p4 = {{acc_V_lcssa_fu_378_p6[37:25]}};

assign p_Result_8_fu_471_p4 = {{acc_V_lcssa_fu_378_p6[37:24]}};

assign p_Result_s_fu_391_p3 = acc_V_lcssa_fu_378_p6[32'd37];

assign p_Val2_1_fu_429_p2 = (zext_ln415_fu_425_p1 + p_Val2_s_fu_399_p4);

assign p_Val2_s_fu_399_p4 = {{acc_V_lcssa_fu_378_p6[23:8]}};

assign select_ln384_fu_589_p3 = ((overflow_reg_695[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign shl_ln_fu_348_p3 = {{trunc_ln1169_fu_344_p1}, {5'd0}};

assign sub_fu_304_p2 = ($signed(row_size) + $signed(32'd4294967295));

assign tmp_10_fu_501_p3 = acc_V_lcssa_fu_378_p6[32'd24];

assign tmp_fu_417_p3 = acc_V_lcssa_fu_378_p6[32'd7];

assign trunc_ln1169_fu_344_p1 = k_reg_240[5:0];

assign underflow_fu_577_p2 = (xor_ln795_fu_571_p2 & p_Result_s_fu_391_p3);

assign val_V_fu_596_p3 = ((or_ln384_reg_700[0:0] == 1'b1) ? select_ln384_fu_589_p3 : p_Val2_1_reg_690);

assign xor_ln416_fu_443_p2 = (p_Result_2_fu_435_p3 ^ 1'd1);

assign xor_ln789_fu_509_p2 = (tmp_10_fu_501_p3 ^ 1'd1);

assign xor_ln794_1_fu_547_p2 = (p_Result_s_fu_391_p3 ^ 1'd1);

assign xor_ln794_fu_535_p2 = (deleted_zeros_fu_493_p3 ^ 1'd1);

assign xor_ln795_fu_571_p2 = (or_ln795_fu_565_p2 ^ 1'd1);

assign zext_ln32_fu_318_p1 = i_fu_172;

assign zext_ln415_fu_425_p1 = tmp_fu_417_p3;

always @ (posedge ap_clk) begin
    shl_ln_reg_675[4:0] <= 5'b00000;
end

endmodule //matVecMul
