-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matVecMul is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 14;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of matVecMul is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matVecMul_matVecMul,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=18.153000,HLS_SYN_LAT=1863,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1765,HLS_SYN_LUT=2510,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv14_3FFF : STD_LOGIC_VECTOR (13 downto 0) := "11111111111111";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal A_0_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal A_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal A_2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal A_3_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal no_of_vectors : STD_LOGIC_VECTOR (31 downto 0);
    signal row_size : STD_LOGIC_VECTOR (31 downto 0);
    signal col_size : STD_LOGIC_VECTOR (31 downto 0);
    signal x_localbuff_V_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_localbuff_V_0_ce0 : STD_LOGIC;
    signal x_localbuff_V_0_we0 : STD_LOGIC;
    signal x_localbuff_V_0_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_localbuff_V_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_localbuff_V_1_ce0 : STD_LOGIC;
    signal x_localbuff_V_1_we0 : STD_LOGIC;
    signal x_localbuff_V_1_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_localbuff_V_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_localbuff_V_2_ce0 : STD_LOGIC;
    signal x_localbuff_V_2_we0 : STD_LOGIC;
    signal x_localbuff_V_2_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_localbuff_V_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_localbuff_V_3_ce0 : STD_LOGIC;
    signal x_localbuff_V_3_we0 : STD_LOGIC;
    signal x_localbuff_V_3_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal col_size_read_reg_614 : STD_LOGIC_VECTOR (31 downto 0);
    signal row_size_read_reg_620 : STD_LOGIC_VECTOR (31 downto 0);
    signal no_of_vectors_read_reg_625 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_fu_304_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_reg_654 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln32_fu_327_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln32_reg_662 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal add_ln44_fu_338_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln44_reg_670 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal shl_ln_fu_348_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_reg_675 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln44_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pkt_last_V_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_pkt_last_V_reg_680 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_return : STD_LOGIC_VECTOR (1 downto 0);
    signal targetBlock_reg_685 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal p_Val2_1_fu_429_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_1_reg_690 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal overflow_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_reg_695 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln384_fu_583_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln384_reg_700 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_ap_done : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_ap_idle : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_ap_ready : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_in_stream_TREADY : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_we0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_we0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_we0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_we0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_done : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_idle : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_ready : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out : STD_LOGIC_VECTOR (37 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out_ap_vld : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out : STD_LOGIC_VECTOR (37 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out_ap_vld : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out : STD_LOGIC_VECTOR (37 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out_ap_vld : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out : STD_LOGIC_VECTOR (37 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out_ap_vld : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_ce0 : STD_LOGIC;
    signal k_reg_240 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg : STD_LOGIC := '0';
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal icmp_ln32_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg : STD_LOGIC := '0';
    signal acc_V_0_loc_fu_188 : STD_LOGIC_VECTOR (37 downto 0);
    signal select_ln340_2_loc_fu_184 : STD_LOGIC_VECTOR (37 downto 0);
    signal select_ln340_1_loc_fu_180 : STD_LOGIC_VECTOR (37 downto 0);
    signal select_ln340_loc_fu_176 : STD_LOGIC_VECTOR (37 downto 0);
    signal i_fu_172 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln32_fu_318_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1169_fu_344_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal acc_V_lcssa_fu_378_p6 : STD_LOGIC_VECTOR (37 downto 0);
    signal tmp_fu_417_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_fu_425_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_s_fu_399_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_2_fu_435_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_1_fu_409_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_fu_443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_7_fu_455_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_8_fu_471_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal carry_1_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_501_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln789_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln789_fu_515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_493_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln794_fu_535_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_391_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln794_fu_541_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln794_1_fu_547_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_521_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln790_fu_529_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln795_fu_559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln795_fu_565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln795_fu_571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_577_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln384_fu_589_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal val_V_fu_596_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matVecMul_matVecMul_Pipeline_sample_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        col_size : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        x_localbuff_V_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_localbuff_V_0_ce0 : OUT STD_LOGIC;
        x_localbuff_V_0_we0 : OUT STD_LOGIC;
        x_localbuff_V_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        x_localbuff_V_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_localbuff_V_1_ce0 : OUT STD_LOGIC;
        x_localbuff_V_1_we0 : OUT STD_LOGIC;
        x_localbuff_V_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        x_localbuff_V_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_localbuff_V_2_ce0 : OUT STD_LOGIC;
        x_localbuff_V_2_we0 : OUT STD_LOGIC;
        x_localbuff_V_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        x_localbuff_V_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_localbuff_V_3_ce0 : OUT STD_LOGIC;
        x_localbuff_V_3_we0 : OUT STD_LOGIC;
        x_localbuff_V_3_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matVecMul_matVecMul_Pipeline_matmul_inner_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln32 : IN STD_LOGIC_VECTOR (31 downto 0);
        shl_ln : IN STD_LOGIC_VECTOR (10 downto 0);
        A_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        A_0_ce0 : OUT STD_LOGIC;
        A_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        A_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        A_1_ce0 : OUT STD_LOGIC;
        A_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        A_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        A_2_ce0 : OUT STD_LOGIC;
        A_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        A_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        A_3_ce0 : OUT STD_LOGIC;
        A_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        acc_V_0_out : OUT STD_LOGIC_VECTOR (37 downto 0);
        acc_V_0_out_ap_vld : OUT STD_LOGIC;
        select_ln340_2_out : OUT STD_LOGIC_VECTOR (37 downto 0);
        select_ln340_2_out_ap_vld : OUT STD_LOGIC;
        select_ln340_1_out : OUT STD_LOGIC_VECTOR (37 downto 0);
        select_ln340_1_out_ap_vld : OUT STD_LOGIC;
        select_ln340_out : OUT STD_LOGIC_VECTOR (37 downto 0);
        select_ln340_out_ap_vld : OUT STD_LOGIC;
        x_localbuff_V_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_localbuff_V_3_ce0 : OUT STD_LOGIC;
        x_localbuff_V_3_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        x_localbuff_V_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_localbuff_V_2_ce0 : OUT STD_LOGIC;
        x_localbuff_V_2_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        x_localbuff_V_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_localbuff_V_1_ce0 : OUT STD_LOGIC;
        x_localbuff_V_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        x_localbuff_V_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        x_localbuff_V_0_ce0 : OUT STD_LOGIC;
        x_localbuff_V_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component matVecMul_mux_42_38_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (37 downto 0);
        din1 : IN STD_LOGIC_VECTOR (37 downto 0);
        din2 : IN STD_LOGIC_VECTOR (37 downto 0);
        din3 : IN STD_LOGIC_VECTOR (37 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (37 downto 0) );
    end component;


    component matVecMul_x_localbuff_V_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matVecMul_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        no_of_vectors : OUT STD_LOGIC_VECTOR (31 downto 0);
        row_size : OUT STD_LOGIC_VECTOR (31 downto 0);
        col_size : OUT STD_LOGIC_VECTOR (31 downto 0);
        A_0_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        A_0_ce0 : IN STD_LOGIC;
        A_0_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        A_1_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        A_1_ce0 : IN STD_LOGIC;
        A_1_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        A_2_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        A_2_ce0 : IN STD_LOGIC;
        A_2_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        A_3_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        A_3_ce0 : IN STD_LOGIC;
        A_3_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component matVecMul_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    x_localbuff_V_0_U : component matVecMul_x_localbuff_V_0
    generic map (
        DataWidth => 16,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => x_localbuff_V_0_address0,
        ce0 => x_localbuff_V_0_ce0,
        we0 => x_localbuff_V_0_we0,
        d0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_d0,
        q0 => x_localbuff_V_0_q0);

    x_localbuff_V_1_U : component matVecMul_x_localbuff_V_0
    generic map (
        DataWidth => 16,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => x_localbuff_V_1_address0,
        ce0 => x_localbuff_V_1_ce0,
        we0 => x_localbuff_V_1_we0,
        d0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_d0,
        q0 => x_localbuff_V_1_q0);

    x_localbuff_V_2_U : component matVecMul_x_localbuff_V_0
    generic map (
        DataWidth => 16,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => x_localbuff_V_2_address0,
        ce0 => x_localbuff_V_2_ce0,
        we0 => x_localbuff_V_2_we0,
        d0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_d0,
        q0 => x_localbuff_V_2_q0);

    x_localbuff_V_3_U : component matVecMul_x_localbuff_V_0
    generic map (
        DataWidth => 16,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => x_localbuff_V_3_address0,
        ce0 => x_localbuff_V_3_ce0,
        we0 => x_localbuff_V_3_we0,
        d0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_d0,
        q0 => x_localbuff_V_3_q0);

    grp_matVecMul_Pipeline_sample_loop_fu_251 : component matVecMul_matVecMul_Pipeline_sample_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start,
        ap_done => grp_matVecMul_Pipeline_sample_loop_fu_251_ap_done,
        ap_idle => grp_matVecMul_Pipeline_sample_loop_fu_251_ap_idle,
        ap_ready => grp_matVecMul_Pipeline_sample_loop_fu_251_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        col_size => col_size_read_reg_614,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_matVecMul_Pipeline_sample_loop_fu_251_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TUSER => in_stream_TUSER_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        in_stream_TID => in_stream_TID_int_regslice,
        in_stream_TDEST => in_stream_TDEST_int_regslice,
        x_localbuff_V_0_address0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_address0,
        x_localbuff_V_0_ce0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_ce0,
        x_localbuff_V_0_we0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_we0,
        x_localbuff_V_0_d0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_d0,
        x_localbuff_V_1_address0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_address0,
        x_localbuff_V_1_ce0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_ce0,
        x_localbuff_V_1_we0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_we0,
        x_localbuff_V_1_d0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_d0,
        x_localbuff_V_2_address0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_address0,
        x_localbuff_V_2_ce0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_ce0,
        x_localbuff_V_2_we0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_we0,
        x_localbuff_V_2_d0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_d0,
        x_localbuff_V_3_address0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_address0,
        x_localbuff_V_3_ce0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_ce0,
        x_localbuff_V_3_we0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_we0,
        x_localbuff_V_3_d0 => grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_d0);

    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278 : component matVecMul_matVecMul_Pipeline_matmul_inner_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start,
        ap_done => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_done,
        ap_idle => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_idle,
        ap_ready => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_ready,
        zext_ln32 => col_size_read_reg_614,
        shl_ln => shl_ln_reg_675,
        A_0_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_address0,
        A_0_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_ce0,
        A_0_q0 => A_0_q0,
        A_1_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_address0,
        A_1_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_ce0,
        A_1_q0 => A_1_q0,
        A_2_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_address0,
        A_2_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_ce0,
        A_2_q0 => A_2_q0,
        A_3_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_address0,
        A_3_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_ce0,
        A_3_q0 => A_3_q0,
        acc_V_0_out => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out,
        acc_V_0_out_ap_vld => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out_ap_vld,
        select_ln340_2_out => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out,
        select_ln340_2_out_ap_vld => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out_ap_vld,
        select_ln340_1_out => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out,
        select_ln340_1_out_ap_vld => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out_ap_vld,
        select_ln340_out => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out,
        select_ln340_out_ap_vld => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out_ap_vld,
        x_localbuff_V_3_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_address0,
        x_localbuff_V_3_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_ce0,
        x_localbuff_V_3_q0 => x_localbuff_V_3_q0,
        x_localbuff_V_2_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_address0,
        x_localbuff_V_2_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_ce0,
        x_localbuff_V_2_q0 => x_localbuff_V_2_q0,
        x_localbuff_V_1_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_address0,
        x_localbuff_V_1_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_ce0,
        x_localbuff_V_1_q0 => x_localbuff_V_1_q0,
        x_localbuff_V_0_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_address0,
        x_localbuff_V_0_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_ce0,
        x_localbuff_V_0_q0 => x_localbuff_V_0_q0,
        ap_return => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_return);

    control_s_axi_U : component matVecMul_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        no_of_vectors => no_of_vectors,
        row_size => row_size,
        col_size => col_size,
        A_0_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_address0,
        A_0_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_0_ce0,
        A_0_q0 => A_0_q0,
        A_1_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_address0,
        A_1_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_1_ce0,
        A_1_q0 => A_1_q0,
        A_2_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_address0,
        A_2_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_2_ce0,
        A_2_q0 => A_2_q0,
        A_3_address0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_address0,
        A_3_ce0 => grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_A_3_ce0,
        A_3_q0 => A_3_q0,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mux_42_38_1_1_U32 : component matVecMul_mux_42_38_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 38,
        din1_WIDTH => 38,
        din2_WIDTH => 38,
        din3_WIDTH => 38,
        din4_WIDTH => 2,
        dout_WIDTH => 38)
    port map (
        din0 => acc_V_0_loc_fu_188,
        din1 => select_ln340_2_loc_fu_184,
        din2 => select_ln340_1_loc_fu_180,
        din3 => select_ln340_loc_fu_176,
        din4 => targetBlock_reg_685,
        dout => acc_V_lcssa_fu_378_p6);

    regslice_both_in_stream_V_data_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_pkt_last_V_reg_680,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln44_fu_333_p2 = ap_const_lv1_0))) then 
                    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_ready = ap_const_logic_1)) then 
                    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln32_fu_322_p2 = ap_const_lv1_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matVecMul_Pipeline_sample_loop_fu_251_ap_ready = ap_const_logic_1)) then 
                    grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_172_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_172 <= ap_const_lv31_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln44_fu_333_p2 = ap_const_lv1_1))) then 
                i_fu_172 <= add_ln32_reg_662;
            end if; 
        end if;
    end process;

    k_reg_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                k_reg_240 <= ap_const_lv32_0;
            elsif (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                k_reg_240 <= add_ln44_reg_670;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                acc_V_0_loc_fu_188 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_acc_V_0_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln32_reg_662 <= add_ln32_fu_327_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln44_reg_670 <= add_ln44_fu_338_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                col_size_read_reg_614 <= col_size;
                no_of_vectors_read_reg_625 <= no_of_vectors;
                row_size_read_reg_620 <= row_size;
                sub_reg_654 <= sub_fu_304_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                or_ln384_reg_700 <= or_ln384_fu_583_p2;
                overflow_reg_695 <= overflow_fu_553_p2;
                p_Val2_1_reg_690 <= p_Val2_1_fu_429_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln44_fu_333_p2 = ap_const_lv1_0))) then
                out_pkt_last_V_reg_680 <= out_pkt_last_V_fu_357_p2;
                    shl_ln_reg_675(10 downto 5) <= shl_ln_fu_348_p3(10 downto 5);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                select_ln340_1_loc_fu_180 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                select_ln340_2_loc_fu_184 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_2_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                select_ln340_loc_fu_176 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_select_ln340_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                targetBlock_reg_685 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_return;
            end if;
        end if;
    end process;
    shl_ln_reg_675(4 downto 0) <= "00000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state2, ap_CS_fsm_state5, icmp_ln44_fu_333_p2, ap_CS_fsm_state6, grp_matVecMul_Pipeline_sample_loop_fu_251_ap_done, grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_done, regslice_both_out_stream_V_data_V_U_apdone_blk, icmp_ln32_fu_322_p2, ap_CS_fsm_state3, out_stream_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln32_fu_322_p2 = ap_const_lv1_0) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((icmp_ln32_fu_322_p2 = ap_const_lv1_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_matVecMul_Pipeline_sample_loop_fu_251_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln44_fu_333_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    Range1_all_ones_fu_481_p2 <= "1" when (p_Result_8_fu_471_p4 = ap_const_lv14_3FFF) else "0";
    Range1_all_zeros_fu_487_p2 <= "1" when (p_Result_8_fu_471_p4 = ap_const_lv14_0) else "0";
    Range2_all_ones_fu_465_p2 <= "1" when (p_Result_7_fu_455_p4 = ap_const_lv13_1FFF) else "0";
    add_ln32_fu_327_p2 <= std_logic_vector(unsigned(i_fu_172) + unsigned(ap_const_lv31_1));
    add_ln44_fu_338_p2 <= std_logic_vector(unsigned(k_reg_240) + unsigned(ap_const_lv32_1));
    and_ln789_fu_515_p2 <= (xor_ln789_fu_509_p2 and Range2_all_ones_fu_465_p2);
    and_ln790_fu_529_p2 <= (carry_1_fu_449_p2 and Range1_all_ones_fu_481_p2);
    and_ln795_fu_559_p2 <= (p_Result_2_fu_435_p3 and deleted_ones_fu_521_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(grp_matVecMul_Pipeline_sample_loop_fu_251_ap_done)
    begin
        if ((grp_matVecMul_Pipeline_sample_loop_fu_251_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_done)
    begin
        if ((grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(out_stream_TREADY_int_regslice)
    begin
        if ((out_stream_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(out_stream_TREADY_int_regslice)
    begin
        if ((out_stream_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, regslice_both_out_stream_V_data_V_U_apdone_blk, icmp_ln32_fu_322_p2)
    begin
        if (((icmp_ln32_fu_322_p2 = ap_const_lv1_0) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, regslice_both_out_stream_V_data_V_U_apdone_blk, icmp_ln32_fu_322_p2)
    begin
        if (((icmp_ln32_fu_322_p2 = ap_const_lv1_0) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    carry_1_fu_449_p2 <= (xor_ln416_fu_443_p2 and p_Result_1_fu_409_p3);
    deleted_ones_fu_521_p3 <= 
        and_ln789_fu_515_p2 when (carry_1_fu_449_p2(0) = '1') else 
        Range1_all_ones_fu_481_p2;
    deleted_zeros_fu_493_p3 <= 
        Range1_all_ones_fu_481_p2 when (carry_1_fu_449_p2(0) = '1') else 
        Range1_all_zeros_fu_487_p2;
    grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_ap_start_reg;
    grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start <= grp_matVecMul_Pipeline_sample_loop_fu_251_ap_start_reg;
    icmp_ln32_fu_322_p2 <= "1" when (signed(zext_ln32_fu_318_p1) < signed(no_of_vectors_read_reg_625)) else "0";
    icmp_ln44_fu_333_p2 <= "1" when (k_reg_240 = row_size_read_reg_620) else "0";
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_matVecMul_Pipeline_sample_loop_fu_251_in_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_stream_TREADY_int_regslice <= grp_matVecMul_Pipeline_sample_loop_fu_251_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    or_ln384_fu_583_p2 <= (underflow_fu_577_p2 or overflow_fu_553_p2);
    or_ln794_fu_541_p2 <= (xor_ln794_fu_535_p2 or p_Result_2_fu_435_p3);
    or_ln795_fu_565_p2 <= (and_ln795_fu_559_p2 or and_ln790_fu_529_p2);
    out_pkt_last_V_fu_357_p2 <= "1" when (k_reg_240 = sub_reg_654) else "0";

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state9, out_stream_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val_V_fu_596_p3),32));
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state8, out_stream_TREADY_int_regslice)
    begin
        if (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    overflow_fu_553_p2 <= (xor_ln794_1_fu_547_p2 and or_ln794_fu_541_p2);
    p_Result_1_fu_409_p3 <= acc_V_lcssa_fu_378_p6(23 downto 23);
    p_Result_2_fu_435_p3 <= p_Val2_1_fu_429_p2(15 downto 15);
    p_Result_7_fu_455_p4 <= acc_V_lcssa_fu_378_p6(37 downto 25);
    p_Result_8_fu_471_p4 <= acc_V_lcssa_fu_378_p6(37 downto 24);
    p_Result_s_fu_391_p3 <= acc_V_lcssa_fu_378_p6(37 downto 37);
    p_Val2_1_fu_429_p2 <= std_logic_vector(unsigned(zext_ln415_fu_425_p1) + unsigned(p_Val2_s_fu_399_p4));
    p_Val2_s_fu_399_p4 <= acc_V_lcssa_fu_378_p6(23 downto 8);
    select_ln384_fu_589_p3 <= 
        ap_const_lv16_7FFF when (overflow_reg_695(0) = '1') else 
        ap_const_lv16_8000;
    shl_ln_fu_348_p3 <= (trunc_ln1169_fu_344_p1 & ap_const_lv5_0);
    sub_fu_304_p2 <= std_logic_vector(unsigned(row_size) + unsigned(ap_const_lv32_FFFFFFFF));
    tmp_10_fu_501_p3 <= acc_V_lcssa_fu_378_p6(24 downto 24);
    tmp_fu_417_p3 <= acc_V_lcssa_fu_378_p6(7 downto 7);
    trunc_ln1169_fu_344_p1 <= k_reg_240(6 - 1 downto 0);
    underflow_fu_577_p2 <= (xor_ln795_fu_571_p2 and p_Result_s_fu_391_p3);
    val_V_fu_596_p3 <= 
        select_ln384_fu_589_p3 when (or_ln384_reg_700(0) = '1') else 
        p_Val2_1_reg_690;

    x_localbuff_V_0_address0_assign_proc : process(ap_CS_fsm_state6, grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_address0, grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_localbuff_V_0_address0 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_0_address0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_address0;
        else 
            x_localbuff_V_0_address0 <= "XXXX";
        end if; 
    end process;


    x_localbuff_V_0_ce0_assign_proc : process(ap_CS_fsm_state6, grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_ce0, grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_localbuff_V_0_ce0 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_0_ce0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_ce0;
        else 
            x_localbuff_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_localbuff_V_0_we0_assign_proc : process(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_0_we0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_0_we0;
        else 
            x_localbuff_V_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_localbuff_V_1_address0_assign_proc : process(ap_CS_fsm_state6, grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_address0, grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_localbuff_V_1_address0 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_1_address0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_address0;
        else 
            x_localbuff_V_1_address0 <= "XXXX";
        end if; 
    end process;


    x_localbuff_V_1_ce0_assign_proc : process(ap_CS_fsm_state6, grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_ce0, grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_localbuff_V_1_ce0 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_1_ce0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_ce0;
        else 
            x_localbuff_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_localbuff_V_1_we0_assign_proc : process(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_1_we0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_1_we0;
        else 
            x_localbuff_V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_localbuff_V_2_address0_assign_proc : process(ap_CS_fsm_state6, grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_address0, grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_localbuff_V_2_address0 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_2_address0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_address0;
        else 
            x_localbuff_V_2_address0 <= "XXXX";
        end if; 
    end process;


    x_localbuff_V_2_ce0_assign_proc : process(ap_CS_fsm_state6, grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_ce0, grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_localbuff_V_2_ce0 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_2_ce0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_ce0;
        else 
            x_localbuff_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_localbuff_V_2_we0_assign_proc : process(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_2_we0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_2_we0;
        else 
            x_localbuff_V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_localbuff_V_3_address0_assign_proc : process(ap_CS_fsm_state6, grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_address0, grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_address0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_localbuff_V_3_address0 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_3_address0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_address0;
        else 
            x_localbuff_V_3_address0 <= "XXXX";
        end if; 
    end process;


    x_localbuff_V_3_ce0_assign_proc : process(ap_CS_fsm_state6, grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_ce0, grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_localbuff_V_3_ce0 <= grp_matVecMul_Pipeline_matmul_inner_loop_fu_278_x_localbuff_V_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_3_ce0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_ce0;
        else 
            x_localbuff_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_localbuff_V_3_we0_assign_proc : process(grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_3_we0 <= grp_matVecMul_Pipeline_sample_loop_fu_251_x_localbuff_V_3_we0;
        else 
            x_localbuff_V_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln416_fu_443_p2 <= (p_Result_2_fu_435_p3 xor ap_const_lv1_1);
    xor_ln789_fu_509_p2 <= (tmp_10_fu_501_p3 xor ap_const_lv1_1);
    xor_ln794_1_fu_547_p2 <= (p_Result_s_fu_391_p3 xor ap_const_lv1_1);
    xor_ln794_fu_535_p2 <= (deleted_zeros_fu_493_p3 xor ap_const_lv1_1);
    xor_ln795_fu_571_p2 <= (or_ln795_fu_565_p2 xor ap_const_lv1_1);
    zext_ln32_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_fu_172),32));
    zext_ln415_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_417_p3),16));
end behav;
