#!/usr/bin/env python3
"""Generate FIR filter coefficients and test vectors for lab5.

Produces:
  hls/fir_coeffs.h    -- C header with coefficient array
  input.txt           -- test input signal (one sample per line)
  expected_output.txt -- reference output (one sample per line)

No external dependencies (stdlib math only).
"""

import math
from pathlib import Path

# ---------- Filter parameters ----------
FS_HZ      = 1000.0       # sample rate
FC_HZ      = 100.0        # cutoff frequency
N_TAPS     = 21           # filter length
N_SAMPLES  = 256          # test signal length

# ---------- Design filter (Hamming-windowed sinc) ----------
M = N_TAPS - 1
alpha = 2.0 * FC_HZ / FS_HZ       # normalised cutoff (fraction of fs)

h = []
for i in range(N_TAPS):
    if i == M // 2:
        val = alpha
    else:
        x = i - M / 2.0
        val = math.sin(math.pi * alpha * x) / (math.pi * x)
    # Hamming window
    val *= 0.54 - 0.46 * math.cos(2.0 * math.pi * i / M)
    h.append(val)

# normalise to unity DC gain
s = sum(h)
h = [c / s for c in h]

# ---------- Generate test input ----------
x = []
for i in range(N_SAMPLES):
    t = i / FS_HZ
    val = 0.7 * math.sin(2 * math.pi * 50.0 * t) \
        + 0.3 * math.sin(2 * math.pi * 300.0 * t)
    x.append(val)
# add impulse at sample 0 to exercise transient
x[0] += 1.0

# ---------- Reference output (direct-form FIR) ----------
y = []
state = [0.0] * N_TAPS
for i in range(N_SAMPLES):
    # shift
    for j in range(N_TAPS - 1, 0, -1):
        state[j] = state[j - 1]
    state[0] = x[i]
    # MAC
    acc = sum(h[j] * state[j] for j in range(N_TAPS))
    y.append(acc)

# ---------- Write outputs ----------
here = Path(__file__).resolve().parent

# C header
hdr = here / "hls" / "fir_coeffs.h"
with open(hdr, "w") as f:
    f.write("#ifndef FIR_COEFFS_H\n#define FIR_COEFFS_H\n\n")
    f.write(f"#define N_TAPS {N_TAPS}\n\n")
    f.write("// Low-pass FIR coefficients\n")
    f.write(f"// fc = {FC_HZ} Hz, fs = {FS_HZ} Hz, {N_TAPS} taps, Hamming window\n")
    f.write(f"// Generated by {Path(__file__).name}\n")
    f.write("const data_t coeffs[N_TAPS] = {\n")
    for i, c in enumerate(h):
        comma = "," if i < N_TAPS - 1 else ""
        f.write(f"    {c: .10e}{comma}\n")
    f.write("};\n\n")
    f.write("#endif\n")

# test vectors
with open(here / "input.txt", "w") as f:
    for val in x:
        f.write(f"{val:.10e}\n")

with open(here / "expected_output.txt", "w") as f:
    for val in y:
        f.write(f"{val:.10e}\n")

print(f"Generated {N_TAPS}-tap coefficients -> {hdr}")
print(f"Generated {N_SAMPLES} test samples  -> input.txt, expected_output.txt")
print(f"\nCoefficients (sum = {sum(h):.6f}):")
for i, c in enumerate(h):
    print(f"  h[{i:2d}] = {c: .10e}")
