-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matVecMul is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 14;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of matVecMul is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matVecMul_matVecMul,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.831000,HLS_SYN_LAT=20742,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=431,HLS_SYN_LUT=917,HLS_VERSION=2021_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv38_0 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv14_3FFF : STD_LOGIC_VECTOR (13 downto 0) := "11111111111111";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv38_1FFFFFFFFF : STD_LOGIC_VECTOR (37 downto 0) := "01111111111111111111111111111111111111";
    constant ap_const_lv38_2000000000 : STD_LOGIC_VECTOR (37 downto 0) := "10000000000000000000000000000000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal A_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal A_ce0 : STD_LOGIC;
    signal A_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal row_size : STD_LOGIC_VECTOR (31 downto 0);
    signal col_size : STD_LOGIC_VECTOR (31 downto 0);
    signal x_localbuff_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal x_localbuff_V_ce0 : STD_LOGIC;
    signal x_localbuff_V_we0 : STD_LOGIC;
    signal x_localbuff_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal icmp_ln39_fu_327_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal col_size_read_reg_705 : STD_LOGIC_VECTOR (31 downto 0);
    signal row_size_read_reg_711 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_fu_287_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_reg_717 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln34_fu_300_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln34_reg_728 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal shl_ln_fu_310_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln_reg_733 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln34_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln39_fu_332_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln39_reg_741 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_state6 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal acc_V_fu_682_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_261_ap_done : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_261_ap_idle : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_261_ap_ready : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_261_in_stream_TREADY : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_ce0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_we0 : STD_LOGIC;
    signal grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal j_reg_238 : STD_LOGIC_VECTOR (6 downto 0);
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal acc_V_3_reg_249 : STD_LOGIC_VECTOR (37 downto 0);
    signal grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal zext_ln1169_1_fu_377_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln39_1_fu_322_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_1_fu_166 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln1169_fu_306_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln39_fu_318_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln1169_1_fu_338_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1169_fu_346_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln1169_fu_350_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal lshr_ln_fu_355_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln1169_1_fu_365_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_9_fu_369_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_fu_408_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln415_fu_416_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_s_fu_390_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_1_fu_420_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_4_fu_426_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_3_fu_400_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln416_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_7_fu_446_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Result_8_fu_462_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal carry_1_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_472_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_492_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln789_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln789_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_484_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln794_1_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_fu_382_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln794_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln794_2_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_512_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln790_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln795_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln795_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln795_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_1_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln384_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln384_1_fu_574_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal val_V_fu_588_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_690_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln712_fu_618_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln712_1_fu_622_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal ret_V_fu_628_p2 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln1245_fu_625_p1 : STD_LOGIC_VECTOR (37 downto 0);
    signal acc_V_4_fu_642_p2 : STD_LOGIC_VECTOR (37 downto 0);
    signal p_Result_s_fu_634_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_1_fu_648_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln794_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln340_fu_668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln384_fu_674_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal out_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matVecMul_matVecMul_Pipeline_sample_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        col_size : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        x_localbuff_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        x_localbuff_V_ce0 : OUT STD_LOGIC;
        x_localbuff_V_we0 : OUT STD_LOGIC;
        x_localbuff_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matVecMul_mul_mul_16s_16s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matVecMul_x_localbuff_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matVecMul_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        row_size : OUT STD_LOGIC_VECTOR (31 downto 0);
        col_size : OUT STD_LOGIC_VECTOR (31 downto 0);
        A_address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        A_ce0 : IN STD_LOGIC;
        A_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component matVecMul_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    x_localbuff_V_U : component matVecMul_x_localbuff_V
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => x_localbuff_V_address0,
        ce0 => x_localbuff_V_ce0,
        we0 => x_localbuff_V_we0,
        d0 => grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_d0,
        q0 => x_localbuff_V_q0);

    grp_matVecMul_Pipeline_sample_loop_fu_261 : component matVecMul_matVecMul_Pipeline_sample_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start,
        ap_done => grp_matVecMul_Pipeline_sample_loop_fu_261_ap_done,
        ap_idle => grp_matVecMul_Pipeline_sample_loop_fu_261_ap_idle,
        ap_ready => grp_matVecMul_Pipeline_sample_loop_fu_261_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        col_size => col_size_read_reg_705,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_matVecMul_Pipeline_sample_loop_fu_261_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TUSER => in_stream_TUSER_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        in_stream_TID => in_stream_TID_int_regslice,
        in_stream_TDEST => in_stream_TDEST_int_regslice,
        x_localbuff_V_address0 => grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_address0,
        x_localbuff_V_ce0 => grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_ce0,
        x_localbuff_V_we0 => grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_we0,
        x_localbuff_V_d0 => grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_d0);

    control_s_axi_U : component matVecMul_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        row_size => row_size,
        col_size => col_size,
        A_address0 => A_address0,
        A_ce0 => A_ce0,
        A_q0 => A_q0,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_mul_16s_16s_32_4_1_U10 : component matVecMul_mul_mul_16s_16s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => x_localbuff_V_q0,
        din1 => A_q0,
        ce => ap_const_logic_1,
        dout => grp_fu_690_p2);

    regslice_both_in_stream_V_data_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TLAST_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component matVecMul_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matVecMul_Pipeline_sample_loop_fu_261_ap_ready = ap_const_logic_1)) then 
                    grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    acc_V_3_reg_249_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                acc_V_3_reg_249 <= acc_V_fu_682_p3;
            elsif (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln34_fu_295_p2 = ap_const_lv1_0))) then 
                acc_V_3_reg_249 <= ap_const_lv38_0;
            end if; 
        end if;
    end process;

    i_1_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_1_fu_166 <= ap_const_lv32_0;
            elsif ((not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                i_1_fu_166 <= add_ln34_reg_728;
            end if; 
        end if;
    end process;

    j_reg_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                j_reg_238 <= add_ln39_reg_741;
            elsif (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln34_fu_295_p2 = ap_const_lv1_0))) then 
                j_reg_238 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln34_reg_728 <= add_ln34_fu_300_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                add_ln39_reg_741 <= add_ln39_fu_332_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                col_size_read_reg_705 <= col_size;
                row_size_read_reg_711 <= row_size;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln34_fu_295_p2 = ap_const_lv1_0))) then
                    shl_ln_reg_733(12 downto 7) <= shl_ln_fu_310_p3(12 downto 7);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                sub_reg_717 <= sub_fu_287_p2;
            end if;
        end if;
    end process;
    shl_ln_reg_733(6 downto 0) <= "0000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state6, icmp_ln39_fu_327_p2, ap_CS_fsm_state11, ap_CS_fsm_state5, icmp_ln34_fu_295_p2, ap_block_state6_io, grp_matVecMul_Pipeline_sample_loop_fu_261_ap_done, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_CS_fsm_state3, out_stream_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_matVecMul_Pipeline_sample_loop_fu_261_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln34_fu_295_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln34_fu_295_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if ((not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                elsif ((not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln39_fu_327_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state11 => 
                if (((out_stream_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    A_address0 <= zext_ln1169_1_fu_377_p1(12 - 1 downto 0);

    A_ce0_assign_proc : process(ap_CS_fsm_state6, icmp_ln39_fu_327_p2, ap_block_state6_io, out_stream_TREADY_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            A_ce0 <= ap_const_logic_1;
        else 
            A_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Range1_all_ones_fu_472_p2 <= "1" when (p_Result_8_fu_462_p4 = ap_const_lv14_3FFF) else "0";
    Range1_all_zeros_fu_478_p2 <= "1" when (p_Result_8_fu_462_p4 = ap_const_lv14_0) else "0";
    Range2_all_ones_fu_456_p2 <= "1" when (p_Result_7_fu_446_p4 = ap_const_lv13_1FFF) else "0";
    acc_V_4_fu_642_p2 <= std_logic_vector(signed(acc_V_3_reg_249) + signed(sext_ln1245_fu_625_p1));
    acc_V_fu_682_p3 <= 
        select_ln384_fu_674_p3 when (xor_ln340_fu_668_p2(0) = '1') else 
        acc_V_4_fu_642_p2;
    add_ln1169_fu_350_p2 <= std_logic_vector(unsigned(zext_ln1169_fu_346_p1) + unsigned(shl_ln_reg_733));
    add_ln34_fu_300_p2 <= std_logic_vector(unsigned(i_1_fu_166) + unsigned(ap_const_lv32_1));
    add_ln39_fu_332_p2 <= std_logic_vector(unsigned(j_reg_238) + unsigned(ap_const_lv7_1));
    and_ln789_fu_506_p2 <= (xor_ln789_fu_500_p2 and Range2_all_ones_fu_456_p2);
    and_ln790_fu_520_p2 <= (carry_1_fu_440_p2 and Range1_all_ones_fu_472_p2);
    and_ln795_fu_550_p2 <= (p_Result_4_fu_426_p3 and deleted_ones_fu_512_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(out_stream_TREADY_int_regslice)
    begin
        if ((out_stream_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_matVecMul_Pipeline_sample_loop_fu_261_ap_done)
    begin
        if ((grp_matVecMul_Pipeline_sample_loop_fu_261_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(icmp_ln39_fu_327_p2, ap_block_state6_io, out_stream_TREADY_int_regslice)
    begin
        if (((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state6_assign_proc : process(icmp_ln39_fu_327_p2, out_stream_TREADY_int_regslice)
    begin
                ap_block_state6 <= ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state6_io_assign_proc : process(icmp_ln39_fu_327_p2, out_stream_TREADY_int_regslice)
    begin
                ap_block_state6_io <= ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state5, icmp_ln34_fu_295_p2, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln34_fu_295_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, icmp_ln34_fu_295_p2, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln34_fu_295_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    carry_1_fu_440_p2 <= (xor_ln416_fu_434_p2 and p_Result_3_fu_400_p3);
    deleted_ones_fu_512_p3 <= 
        and_ln789_fu_506_p2 when (carry_1_fu_440_p2(0) = '1') else 
        Range1_all_ones_fu_472_p2;
    deleted_zeros_fu_484_p3 <= 
        Range1_all_ones_fu_472_p2 when (carry_1_fu_440_p2(0) = '1') else 
        Range1_all_zeros_fu_478_p2;
    grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start <= grp_matVecMul_Pipeline_sample_loop_fu_261_ap_start_reg;
    icmp_ln34_fu_295_p2 <= "1" when (i_1_fu_166 = row_size_read_reg_711) else "0";
    icmp_ln39_fu_327_p2 <= "1" when (zext_ln39_fu_318_p1 = col_size_read_reg_705) else "0";
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_matVecMul_Pipeline_sample_loop_fu_261_in_stream_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_stream_TREADY_int_regslice <= grp_matVecMul_Pipeline_sample_loop_fu_261_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln_fu_355_p4 <= add_ln1169_fu_350_p2(12 downto 7);
    or_ln384_fu_582_p2 <= (underflow_fu_568_p2 or overflow_1_fu_544_p2);
    or_ln794_fu_532_p2 <= (xor_ln794_1_fu_526_p2 or p_Result_4_fu_426_p3);
    or_ln795_fu_556_p2 <= (and_ln795_fu_550_p2 or and_ln790_fu_520_p2);

    out_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state6, icmp_ln39_fu_327_p2, ap_CS_fsm_state11, out_stream_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= std_logic_vector(IEEE.numeric_std.resize(unsigned(val_V_fu_588_p3),32));
    out_stream_TLAST_int_regslice <= "1" when (i_1_fu_166 = sub_reg_717) else "0";
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state6, icmp_ln39_fu_327_p2, ap_block_state6_io, out_stream_TREADY_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    overflow_1_fu_544_p2 <= (xor_ln794_2_fu_538_p2 and or_ln794_fu_532_p2);
    overflow_fu_662_p2 <= (xor_ln794_fu_656_p2 and p_Result_1_fu_648_p3);
    p_Result_1_fu_648_p3 <= acc_V_4_fu_642_p2(37 downto 37);
    p_Result_2_fu_382_p3 <= acc_V_3_reg_249(37 downto 37);
    p_Result_3_fu_400_p3 <= acc_V_3_reg_249(23 downto 23);
    p_Result_4_fu_426_p3 <= p_Val2_1_fu_420_p2(15 downto 15);
    p_Result_7_fu_446_p4 <= acc_V_3_reg_249(37 downto 25);
    p_Result_8_fu_462_p4 <= acc_V_3_reg_249(37 downto 24);
    p_Result_s_fu_634_p3 <= ret_V_fu_628_p2(38 downto 38);
    p_Val2_1_fu_420_p2 <= std_logic_vector(unsigned(zext_ln415_fu_416_p1) + unsigned(p_Val2_s_fu_390_p4));
    p_Val2_s_fu_390_p4 <= acc_V_3_reg_249(23 downto 8);
    ret_V_fu_628_p2 <= std_logic_vector(signed(sext_ln712_fu_618_p1) + signed(sext_ln712_1_fu_622_p1));
    select_ln384_1_fu_574_p3 <= 
        ap_const_lv16_7FFF when (overflow_1_fu_544_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln384_fu_674_p3 <= 
        ap_const_lv38_1FFFFFFFFF when (overflow_fu_662_p2(0) = '1') else 
        ap_const_lv38_2000000000;
        sext_ln1245_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_690_p2),38));

        sext_ln712_1_fu_622_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_690_p2),39));

        sext_ln712_fu_618_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(acc_V_3_reg_249),39));

    shl_ln1169_1_fu_338_p3 <= (j_reg_238 & ap_const_lv1_0);
    shl_ln_fu_310_p3 <= (trunc_ln1169_fu_306_p1 & ap_const_lv7_0);
    sub_fu_287_p2 <= std_logic_vector(unsigned(row_size_read_reg_711) + unsigned(ap_const_lv32_FFFFFFFF));
    tmp_2_fu_492_p3 <= acc_V_3_reg_249(24 downto 24);
    tmp_9_fu_369_p3 <= (lshr_ln_fu_355_p4 & trunc_ln1169_1_fu_365_p1);
    tmp_fu_408_p3 <= acc_V_3_reg_249(7 downto 7);
    trunc_ln1169_1_fu_365_p1 <= j_reg_238(6 - 1 downto 0);
    trunc_ln1169_fu_306_p1 <= i_1_fu_166(6 - 1 downto 0);
    underflow_fu_568_p2 <= (xor_ln795_fu_562_p2 and p_Result_2_fu_382_p3);
    val_V_fu_588_p3 <= 
        select_ln384_1_fu_574_p3 when (or_ln384_fu_582_p2(0) = '1') else 
        p_Val2_1_fu_420_p2;

    x_localbuff_V_address0_assign_proc : process(ap_CS_fsm_state6, grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_address0, ap_CS_fsm_state3, zext_ln39_1_fu_322_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            x_localbuff_V_address0 <= zext_ln39_1_fu_322_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_address0 <= grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_address0;
        else 
            x_localbuff_V_address0 <= "XXXXXX";
        end if; 
    end process;


    x_localbuff_V_ce0_assign_proc : process(ap_CS_fsm_state6, icmp_ln39_fu_327_p2, ap_block_state6_io, grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_ce0, ap_CS_fsm_state3, out_stream_TREADY_int_regslice)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state6_io) or ((icmp_ln39_fu_327_p2 = ap_const_lv1_1) and (out_stream_TREADY_int_regslice = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            x_localbuff_V_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_ce0 <= grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_ce0;
        else 
            x_localbuff_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    x_localbuff_V_we0_assign_proc : process(grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            x_localbuff_V_we0 <= grp_matVecMul_Pipeline_sample_loop_fu_261_x_localbuff_V_we0;
        else 
            x_localbuff_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln340_fu_668_p2 <= (p_Result_s_fu_634_p3 xor p_Result_1_fu_648_p3);
    xor_ln416_fu_434_p2 <= (p_Result_4_fu_426_p3 xor ap_const_lv1_1);
    xor_ln789_fu_500_p2 <= (tmp_2_fu_492_p3 xor ap_const_lv1_1);
    xor_ln794_1_fu_526_p2 <= (deleted_zeros_fu_484_p3 xor ap_const_lv1_1);
    xor_ln794_2_fu_538_p2 <= (p_Result_2_fu_382_p3 xor ap_const_lv1_1);
    xor_ln794_fu_656_p2 <= (p_Result_s_fu_634_p3 xor ap_const_lv1_1);
    xor_ln795_fu_562_p2 <= (or_ln795_fu_556_p2 xor ap_const_lv1_1);
    zext_ln1169_1_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_369_p3),64));
    zext_ln1169_fu_346_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1169_1_fu_338_p3),13));
    zext_ln39_1_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_238),64));
    zext_ln39_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_238),32));
    zext_ln415_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_408_p3),16));
end behav;
